package com.atguigu.finance.bean;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.io.Serializable;
import java.util.Date;

public class NplmBorrowerInfo implements Serializable{

    @Id
    @Column
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Integer id;

    @Column
    private Integer applyClientId;
    @Column
    private Integer ecifId;
    @Column
    private String clientName;
    @Column
    private String mobile;
    @Column
    private String oldName;
    @Column
    private String sex;
    @Column
    private String nation;
    @Column
    private String birthday;
    @Column
    private String marital;
    @Column
    private Integer haveChildren;
    @Column
    private Integer childrenCount;
    @Column
    private String nationality;
    @Column
    private String hProvince;
    @Column
    private String hCity;
    @Column
    private String hDress;
    @Column
    private String identityType;
    @Column
    private String identityNum;
    @Column
    private String identityValidDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.HAVE_CAR
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String haveCar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.HOUSE_EXPLAIN
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String houseExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.RESIDE_EXPLAIN
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String resideExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.RESIDE_YEAR
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String resideYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.DEGREE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.DIPLOMA
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String diploma;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.YEAR_INCOME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer yearIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.INDUSTRY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.JOB
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.COMPANY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.COMPANY_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String companyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.DEPARTMENT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.POSITION
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.WORK_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer workTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.WORK_TIME_UNIT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String workTimeUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.CLIENT_AREA
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String clientArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.CLIENT_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String clientType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.F_NATION
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String fNation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.F_PROVINCE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String fProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.F_CITY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String fCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.F_AREA
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String fArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.F_STREET
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String fStreet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.F_ZIPCODE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String fZipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.C_NATION
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String cNation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.C_PROVINCE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String cProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.C_CITY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String cCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.C_AREA
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String cArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.C_STREET
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String cStreet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.C_ZIPCODE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String cZipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.MOBILE1
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String mobile1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.MOBILE2
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String mobile2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.MOBILE3
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String mobile3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.F_TEL1
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String fTel1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.F_TEL2
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String fTel2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.F_TEL3
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String fTel3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.C_TEL1
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String cTel1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.C_TEL2
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String cTel2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.C_TEL3
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String cTel3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.EMAIL1
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String email1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.EMAIL2
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String email2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.EMAIL3
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String email3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.CREDIT_AMOUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer creditAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.SOCIALl_SECURITY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String sociallSecurity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.CREATOR
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.UPDATER
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_borrower_info.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String updateType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.id
     *
     * @return the value of nplm_borrower_info.id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.id
     *
     * @param id the value for nplm_borrower_info.id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.APPLY_CLIENT_ID
     *
     * @return the value of nplm_borrower_info.APPLY_CLIENT_ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getApplyClientId() {
        return applyClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.APPLY_CLIENT_ID
     *
     * @param applyClientId the value for nplm_borrower_info.APPLY_CLIENT_ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setApplyClientId(Integer applyClientId) {
        this.applyClientId = applyClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.ECIF_ID
     *
     * @return the value of nplm_borrower_info.ECIF_ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getEcifId() {
        return ecifId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.ECIF_ID
     *
     * @param ecifId the value for nplm_borrower_info.ECIF_ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setEcifId(Integer ecifId) {
        this.ecifId = ecifId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.CLIENT_NAME
     *
     * @return the value of nplm_borrower_info.CLIENT_NAME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.CLIENT_NAME
     *
     * @param clientName the value for nplm_borrower_info.CLIENT_NAME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.MOBILE
     *
     * @return the value of nplm_borrower_info.MOBILE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.MOBILE
     *
     * @param mobile the value for nplm_borrower_info.MOBILE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.OLD_NAME
     *
     * @return the value of nplm_borrower_info.OLD_NAME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getOldName() {
        return oldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.OLD_NAME
     *
     * @param oldName the value for nplm_borrower_info.OLD_NAME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setOldName(String oldName) {
        this.oldName = oldName == null ? null : oldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.SEX
     *
     * @return the value of nplm_borrower_info.SEX
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.SEX
     *
     * @param sex the value for nplm_borrower_info.SEX
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.NATION
     *
     * @return the value of nplm_borrower_info.NATION
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.NATION
     *
     * @param nation the value for nplm_borrower_info.NATION
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.BIRTHDAY
     *
     * @return the value of nplm_borrower_info.BIRTHDAY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.BIRTHDAY
     *
     * @param birthday the value for nplm_borrower_info.BIRTHDAY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.MARITAL
     *
     * @return the value of nplm_borrower_info.MARITAL
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getMarital() {
        return marital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.MARITAL
     *
     * @param marital the value for nplm_borrower_info.MARITAL
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setMarital(String marital) {
        this.marital = marital == null ? null : marital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.HAVE_CHILDREN
     *
     * @return the value of nplm_borrower_info.HAVE_CHILDREN
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getHaveChildren() {
        return haveChildren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.HAVE_CHILDREN
     *
     * @param haveChildren the value for nplm_borrower_info.HAVE_CHILDREN
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setHaveChildren(Integer haveChildren) {
        this.haveChildren = haveChildren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.CHILDREN_COUNT
     *
     * @return the value of nplm_borrower_info.CHILDREN_COUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getChildrenCount() {
        return childrenCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.CHILDREN_COUNT
     *
     * @param childrenCount the value for nplm_borrower_info.CHILDREN_COUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setChildrenCount(Integer childrenCount) {
        this.childrenCount = childrenCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.NATIONALITY
     *
     * @return the value of nplm_borrower_info.NATIONALITY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.NATIONALITY
     *
     * @param nationality the value for nplm_borrower_info.NATIONALITY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.H_PROVINCE
     *
     * @return the value of nplm_borrower_info.H_PROVINCE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String gethProvince() {
        return hProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.H_PROVINCE
     *
     * @param hProvince the value for nplm_borrower_info.H_PROVINCE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void sethProvince(String hProvince) {
        this.hProvince = hProvince == null ? null : hProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.H_CITY
     *
     * @return the value of nplm_borrower_info.H_CITY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String gethCity() {
        return hCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.H_CITY
     *
     * @param hCity the value for nplm_borrower_info.H_CITY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void sethCity(String hCity) {
        this.hCity = hCity == null ? null : hCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.H_DRESS
     *
     * @return the value of nplm_borrower_info.H_DRESS
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String gethDress() {
        return hDress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.H_DRESS
     *
     * @param hDress the value for nplm_borrower_info.H_DRESS
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void sethDress(String hDress) {
        this.hDress = hDress == null ? null : hDress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.IDENTITY_TYPE
     *
     * @return the value of nplm_borrower_info.IDENTITY_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getIdentityType() {
        return identityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.IDENTITY_TYPE
     *
     * @param identityType the value for nplm_borrower_info.IDENTITY_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setIdentityType(String identityType) {
        this.identityType = identityType == null ? null : identityType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.IDENTITY_NUM
     *
     * @return the value of nplm_borrower_info.IDENTITY_NUM
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getIdentityNum() {
        return identityNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.IDENTITY_NUM
     *
     * @param identityNum the value for nplm_borrower_info.IDENTITY_NUM
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setIdentityNum(String identityNum) {
        this.identityNum = identityNum == null ? null : identityNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.IDENTITY_VALID_DATE
     *
     * @return the value of nplm_borrower_info.IDENTITY_VALID_DATE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getIdentityValidDate() {
        return identityValidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.IDENTITY_VALID_DATE
     *
     * @param identityValidDate the value for nplm_borrower_info.IDENTITY_VALID_DATE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setIdentityValidDate(String identityValidDate) {
        this.identityValidDate = identityValidDate == null ? null : identityValidDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.HAVE_CAR
     *
     * @return the value of nplm_borrower_info.HAVE_CAR
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getHaveCar() {
        return haveCar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.HAVE_CAR
     *
     * @param haveCar the value for nplm_borrower_info.HAVE_CAR
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setHaveCar(String haveCar) {
        this.haveCar = haveCar == null ? null : haveCar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.HOUSE_EXPLAIN
     *
     * @return the value of nplm_borrower_info.HOUSE_EXPLAIN
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getHouseExplain() {
        return houseExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.HOUSE_EXPLAIN
     *
     * @param houseExplain the value for nplm_borrower_info.HOUSE_EXPLAIN
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setHouseExplain(String houseExplain) {
        this.houseExplain = houseExplain == null ? null : houseExplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.RESIDE_EXPLAIN
     *
     * @return the value of nplm_borrower_info.RESIDE_EXPLAIN
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getResideExplain() {
        return resideExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.RESIDE_EXPLAIN
     *
     * @param resideExplain the value for nplm_borrower_info.RESIDE_EXPLAIN
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setResideExplain(String resideExplain) {
        this.resideExplain = resideExplain == null ? null : resideExplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.RESIDE_YEAR
     *
     * @return the value of nplm_borrower_info.RESIDE_YEAR
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getResideYear() {
        return resideYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.RESIDE_YEAR
     *
     * @param resideYear the value for nplm_borrower_info.RESIDE_YEAR
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setResideYear(String resideYear) {
        this.resideYear = resideYear == null ? null : resideYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.DEGREE
     *
     * @return the value of nplm_borrower_info.DEGREE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.DEGREE
     *
     * @param degree the value for nplm_borrower_info.DEGREE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.DIPLOMA
     *
     * @return the value of nplm_borrower_info.DIPLOMA
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getDiploma() {
        return diploma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.DIPLOMA
     *
     * @param diploma the value for nplm_borrower_info.DIPLOMA
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setDiploma(String diploma) {
        this.diploma = diploma == null ? null : diploma.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.YEAR_INCOME
     *
     * @return the value of nplm_borrower_info.YEAR_INCOME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getYearIncome() {
        return yearIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.YEAR_INCOME
     *
     * @param yearIncome the value for nplm_borrower_info.YEAR_INCOME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setYearIncome(Integer yearIncome) {
        this.yearIncome = yearIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.INDUSTRY
     *
     * @return the value of nplm_borrower_info.INDUSTRY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.INDUSTRY
     *
     * @param industry the value for nplm_borrower_info.INDUSTRY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.JOB
     *
     * @return the value of nplm_borrower_info.JOB
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.JOB
     *
     * @param job the value for nplm_borrower_info.JOB
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.COMPANY
     *
     * @return the value of nplm_borrower_info.COMPANY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.COMPANY
     *
     * @param company the value for nplm_borrower_info.COMPANY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.COMPANY_TYPE
     *
     * @return the value of nplm_borrower_info.COMPANY_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.COMPANY_TYPE
     *
     * @param companyType the value for nplm_borrower_info.COMPANY_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setCompanyType(String companyType) {
        this.companyType = companyType == null ? null : companyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.DEPARTMENT
     *
     * @return the value of nplm_borrower_info.DEPARTMENT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.DEPARTMENT
     *
     * @param department the value for nplm_borrower_info.DEPARTMENT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.POSITION
     *
     * @return the value of nplm_borrower_info.POSITION
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.POSITION
     *
     * @param position the value for nplm_borrower_info.POSITION
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.WORK_TIME
     *
     * @return the value of nplm_borrower_info.WORK_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getWorkTime() {
        return workTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.WORK_TIME
     *
     * @param workTime the value for nplm_borrower_info.WORK_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setWorkTime(Integer workTime) {
        this.workTime = workTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.WORK_TIME_UNIT
     *
     * @return the value of nplm_borrower_info.WORK_TIME_UNIT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getWorkTimeUnit() {
        return workTimeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.WORK_TIME_UNIT
     *
     * @param workTimeUnit the value for nplm_borrower_info.WORK_TIME_UNIT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setWorkTimeUnit(String workTimeUnit) {
        this.workTimeUnit = workTimeUnit == null ? null : workTimeUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.CLIENT_AREA
     *
     * @return the value of nplm_borrower_info.CLIENT_AREA
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getClientArea() {
        return clientArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.CLIENT_AREA
     *
     * @param clientArea the value for nplm_borrower_info.CLIENT_AREA
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setClientArea(String clientArea) {
        this.clientArea = clientArea == null ? null : clientArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.CLIENT_TYPE
     *
     * @return the value of nplm_borrower_info.CLIENT_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.CLIENT_TYPE
     *
     * @param clientType the value for nplm_borrower_info.CLIENT_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setClientType(String clientType) {
        this.clientType = clientType == null ? null : clientType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.F_NATION
     *
     * @return the value of nplm_borrower_info.F_NATION
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getfNation() {
        return fNation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.F_NATION
     *
     * @param fNation the value for nplm_borrower_info.F_NATION
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setfNation(String fNation) {
        this.fNation = fNation == null ? null : fNation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.F_PROVINCE
     *
     * @return the value of nplm_borrower_info.F_PROVINCE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getfProvince() {
        return fProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.F_PROVINCE
     *
     * @param fProvince the value for nplm_borrower_info.F_PROVINCE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setfProvince(String fProvince) {
        this.fProvince = fProvince == null ? null : fProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.F_CITY
     *
     * @return the value of nplm_borrower_info.F_CITY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getfCity() {
        return fCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.F_CITY
     *
     * @param fCity the value for nplm_borrower_info.F_CITY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setfCity(String fCity) {
        this.fCity = fCity == null ? null : fCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.F_AREA
     *
     * @return the value of nplm_borrower_info.F_AREA
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getfArea() {
        return fArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.F_AREA
     *
     * @param fArea the value for nplm_borrower_info.F_AREA
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setfArea(String fArea) {
        this.fArea = fArea == null ? null : fArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.F_STREET
     *
     * @return the value of nplm_borrower_info.F_STREET
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getfStreet() {
        return fStreet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.F_STREET
     *
     * @param fStreet the value for nplm_borrower_info.F_STREET
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setfStreet(String fStreet) {
        this.fStreet = fStreet == null ? null : fStreet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.F_ZIPCODE
     *
     * @return the value of nplm_borrower_info.F_ZIPCODE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getfZipcode() {
        return fZipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.F_ZIPCODE
     *
     * @param fZipcode the value for nplm_borrower_info.F_ZIPCODE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setfZipcode(String fZipcode) {
        this.fZipcode = fZipcode == null ? null : fZipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.C_NATION
     *
     * @return the value of nplm_borrower_info.C_NATION
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getcNation() {
        return cNation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.C_NATION
     *
     * @param cNation the value for nplm_borrower_info.C_NATION
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setcNation(String cNation) {
        this.cNation = cNation == null ? null : cNation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.C_PROVINCE
     *
     * @return the value of nplm_borrower_info.C_PROVINCE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getcProvince() {
        return cProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.C_PROVINCE
     *
     * @param cProvince the value for nplm_borrower_info.C_PROVINCE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setcProvince(String cProvince) {
        this.cProvince = cProvince == null ? null : cProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.C_CITY
     *
     * @return the value of nplm_borrower_info.C_CITY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getcCity() {
        return cCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.C_CITY
     *
     * @param cCity the value for nplm_borrower_info.C_CITY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setcCity(String cCity) {
        this.cCity = cCity == null ? null : cCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.C_AREA
     *
     * @return the value of nplm_borrower_info.C_AREA
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getcArea() {
        return cArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.C_AREA
     *
     * @param cArea the value for nplm_borrower_info.C_AREA
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setcArea(String cArea) {
        this.cArea = cArea == null ? null : cArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.C_STREET
     *
     * @return the value of nplm_borrower_info.C_STREET
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getcStreet() {
        return cStreet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.C_STREET
     *
     * @param cStreet the value for nplm_borrower_info.C_STREET
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setcStreet(String cStreet) {
        this.cStreet = cStreet == null ? null : cStreet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.C_ZIPCODE
     *
     * @return the value of nplm_borrower_info.C_ZIPCODE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getcZipcode() {
        return cZipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.C_ZIPCODE
     *
     * @param cZipcode the value for nplm_borrower_info.C_ZIPCODE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setcZipcode(String cZipcode) {
        this.cZipcode = cZipcode == null ? null : cZipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.MOBILE1
     *
     * @return the value of nplm_borrower_info.MOBILE1
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getMobile1() {
        return mobile1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.MOBILE1
     *
     * @param mobile1 the value for nplm_borrower_info.MOBILE1
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setMobile1(String mobile1) {
        this.mobile1 = mobile1 == null ? null : mobile1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.MOBILE2
     *
     * @return the value of nplm_borrower_info.MOBILE2
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getMobile2() {
        return mobile2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.MOBILE2
     *
     * @param mobile2 the value for nplm_borrower_info.MOBILE2
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setMobile2(String mobile2) {
        this.mobile2 = mobile2 == null ? null : mobile2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.MOBILE3
     *
     * @return the value of nplm_borrower_info.MOBILE3
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getMobile3() {
        return mobile3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.MOBILE3
     *
     * @param mobile3 the value for nplm_borrower_info.MOBILE3
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setMobile3(String mobile3) {
        this.mobile3 = mobile3 == null ? null : mobile3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.F_TEL1
     *
     * @return the value of nplm_borrower_info.F_TEL1
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getfTel1() {
        return fTel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.F_TEL1
     *
     * @param fTel1 the value for nplm_borrower_info.F_TEL1
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setfTel1(String fTel1) {
        this.fTel1 = fTel1 == null ? null : fTel1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.F_TEL2
     *
     * @return the value of nplm_borrower_info.F_TEL2
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getfTel2() {
        return fTel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.F_TEL2
     *
     * @param fTel2 the value for nplm_borrower_info.F_TEL2
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setfTel2(String fTel2) {
        this.fTel2 = fTel2 == null ? null : fTel2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.F_TEL3
     *
     * @return the value of nplm_borrower_info.F_TEL3
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getfTel3() {
        return fTel3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.F_TEL3
     *
     * @param fTel3 the value for nplm_borrower_info.F_TEL3
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setfTel3(String fTel3) {
        this.fTel3 = fTel3 == null ? null : fTel3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.C_TEL1
     *
     * @return the value of nplm_borrower_info.C_TEL1
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getcTel1() {
        return cTel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.C_TEL1
     *
     * @param cTel1 the value for nplm_borrower_info.C_TEL1
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setcTel1(String cTel1) {
        this.cTel1 = cTel1 == null ? null : cTel1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.C_TEL2
     *
     * @return the value of nplm_borrower_info.C_TEL2
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getcTel2() {
        return cTel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.C_TEL2
     *
     * @param cTel2 the value for nplm_borrower_info.C_TEL2
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setcTel2(String cTel2) {
        this.cTel2 = cTel2 == null ? null : cTel2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.C_TEL3
     *
     * @return the value of nplm_borrower_info.C_TEL3
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getcTel3() {
        return cTel3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.C_TEL3
     *
     * @param cTel3 the value for nplm_borrower_info.C_TEL3
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setcTel3(String cTel3) {
        this.cTel3 = cTel3 == null ? null : cTel3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.EMAIL1
     *
     * @return the value of nplm_borrower_info.EMAIL1
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getEmail1() {
        return email1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.EMAIL1
     *
     * @param email1 the value for nplm_borrower_info.EMAIL1
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setEmail1(String email1) {
        this.email1 = email1 == null ? null : email1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.EMAIL2
     *
     * @return the value of nplm_borrower_info.EMAIL2
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getEmail2() {
        return email2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.EMAIL2
     *
     * @param email2 the value for nplm_borrower_info.EMAIL2
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setEmail2(String email2) {
        this.email2 = email2 == null ? null : email2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.EMAIL3
     *
     * @return the value of nplm_borrower_info.EMAIL3
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getEmail3() {
        return email3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.EMAIL3
     *
     * @param email3 the value for nplm_borrower_info.EMAIL3
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setEmail3(String email3) {
        this.email3 = email3 == null ? null : email3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.CREDIT_AMOUNT
     *
     * @return the value of nplm_borrower_info.CREDIT_AMOUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getCreditAmount() {
        return creditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.CREDIT_AMOUNT
     *
     * @param creditAmount the value for nplm_borrower_info.CREDIT_AMOUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setCreditAmount(Integer creditAmount) {
        this.creditAmount = creditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.SOCIALl_SECURITY
     *
     * @return the value of nplm_borrower_info.SOCIALl_SECURITY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getSociallSecurity() {
        return sociallSecurity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.SOCIALl_SECURITY
     *
     * @param sociallSecurity the value for nplm_borrower_info.SOCIALl_SECURITY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setSociallSecurity(String sociallSecurity) {
        this.sociallSecurity = sociallSecurity == null ? null : sociallSecurity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.CREATOR
     *
     * @return the value of nplm_borrower_info.CREATOR
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.CREATOR
     *
     * @param creator the value for nplm_borrower_info.CREATOR
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.CREATE_TIME
     *
     * @return the value of nplm_borrower_info.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.CREATE_TIME
     *
     * @param createTime the value for nplm_borrower_info.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.UPDATER
     *
     * @return the value of nplm_borrower_info.UPDATER
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.UPDATER
     *
     * @param updater the value for nplm_borrower_info.UPDATER
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.UPDATE_TIME
     *
     * @return the value of nplm_borrower_info.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.UPDATE_TIME
     *
     * @param updateTime the value for nplm_borrower_info.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_borrower_info.UPDATE_TYPE
     *
     * @return the value of nplm_borrower_info.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getUpdateType() {
        return updateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_borrower_info.UPDATE_TYPE
     *
     * @param updateType the value for nplm_borrower_info.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setUpdateType(String updateType) {
        this.updateType = updateType == null ? null : updateType.trim();
    }
}