package com.atguigu.finance.bean;

import javax.persistence.Column;
import java.util.Date;

public class NplmOverdueContract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.id
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.LOAN_CONTRACT_NUM
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String loanContractNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.OVERDUE_STATUS
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String overdueStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.OVERDUE_DAYS
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer overdueDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.INSTALMENT_CNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer instalmentCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.ALL_DAYS
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer allDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.ALL_INSTALMENT_CNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer allInstalmentCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.ALL_NUMBER
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer allNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.PRINCIPAL_INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer principalInterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.ALL_FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer allForfeit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.ALL_AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer allAmerce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.ALL_SHOULD
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer allShould;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.ALL_INDEED
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer allIndeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.CURRENT_REPAY
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer currentRepay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.ALL_REPAYMENT_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer allRepaymentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.FIRST_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String firstDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.START_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.SERIAL_START_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String serialStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.OVERDUE_HISTORY
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String overdueHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.COMPUTE_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String computeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.CREATOR
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.UPDATER
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_overdue_contract.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String updateType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.id
     *
     * @return the value of nplm_overdue_contract.id
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.id
     *
     * @param id the value for nplm_overdue_contract.id
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.LOAN_CONTRACT_NUM
     *
     * @return the value of nplm_overdue_contract.LOAN_CONTRACT_NUM
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getLoanContractNum() {
        return loanContractNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.LOAN_CONTRACT_NUM
     *
     * @param loanContractNum the value for nplm_overdue_contract.LOAN_CONTRACT_NUM
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setLoanContractNum(String loanContractNum) {
        this.loanContractNum = loanContractNum == null ? null : loanContractNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.OVERDUE_STATUS
     *
     * @return the value of nplm_overdue_contract.OVERDUE_STATUS
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getOverdueStatus() {
        return overdueStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.OVERDUE_STATUS
     *
     * @param overdueStatus the value for nplm_overdue_contract.OVERDUE_STATUS
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setOverdueStatus(String overdueStatus) {
        this.overdueStatus = overdueStatus == null ? null : overdueStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.OVERDUE_DAYS
     *
     * @return the value of nplm_overdue_contract.OVERDUE_DAYS
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getOverdueDays() {
        return overdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.OVERDUE_DAYS
     *
     * @param overdueDays the value for nplm_overdue_contract.OVERDUE_DAYS
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setOverdueDays(Integer overdueDays) {
        this.overdueDays = overdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.INSTALMENT_CNT
     *
     * @return the value of nplm_overdue_contract.INSTALMENT_CNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getInstalmentCnt() {
        return instalmentCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.INSTALMENT_CNT
     *
     * @param instalmentCnt the value for nplm_overdue_contract.INSTALMENT_CNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setInstalmentCnt(Integer instalmentCnt) {
        this.instalmentCnt = instalmentCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.ALL_DAYS
     *
     * @return the value of nplm_overdue_contract.ALL_DAYS
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getAllDays() {
        return allDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.ALL_DAYS
     *
     * @param allDays the value for nplm_overdue_contract.ALL_DAYS
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAllDays(Integer allDays) {
        this.allDays = allDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.ALL_INSTALMENT_CNT
     *
     * @return the value of nplm_overdue_contract.ALL_INSTALMENT_CNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getAllInstalmentCnt() {
        return allInstalmentCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.ALL_INSTALMENT_CNT
     *
     * @param allInstalmentCnt the value for nplm_overdue_contract.ALL_INSTALMENT_CNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAllInstalmentCnt(Integer allInstalmentCnt) {
        this.allInstalmentCnt = allInstalmentCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.ALL_NUMBER
     *
     * @return the value of nplm_overdue_contract.ALL_NUMBER
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getAllNumber() {
        return allNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.ALL_NUMBER
     *
     * @param allNumber the value for nplm_overdue_contract.ALL_NUMBER
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAllNumber(Integer allNumber) {
        this.allNumber = allNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.PRINCIPAL_INTEREST
     *
     * @return the value of nplm_overdue_contract.PRINCIPAL_INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getPrincipalInterest() {
        return principalInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.PRINCIPAL_INTEREST
     *
     * @param principalInterest the value for nplm_overdue_contract.PRINCIPAL_INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setPrincipalInterest(Integer principalInterest) {
        this.principalInterest = principalInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.ALL_FORFEIT
     *
     * @return the value of nplm_overdue_contract.ALL_FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getAllForfeit() {
        return allForfeit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.ALL_FORFEIT
     *
     * @param allForfeit the value for nplm_overdue_contract.ALL_FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAllForfeit(Integer allForfeit) {
        this.allForfeit = allForfeit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.ALL_AMERCE
     *
     * @return the value of nplm_overdue_contract.ALL_AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getAllAmerce() {
        return allAmerce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.ALL_AMERCE
     *
     * @param allAmerce the value for nplm_overdue_contract.ALL_AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAllAmerce(Integer allAmerce) {
        this.allAmerce = allAmerce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.ALL_SHOULD
     *
     * @return the value of nplm_overdue_contract.ALL_SHOULD
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getAllShould() {
        return allShould;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.ALL_SHOULD
     *
     * @param allShould the value for nplm_overdue_contract.ALL_SHOULD
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAllShould(Integer allShould) {
        this.allShould = allShould;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.ALL_INDEED
     *
     * @return the value of nplm_overdue_contract.ALL_INDEED
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getAllIndeed() {
        return allIndeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.ALL_INDEED
     *
     * @param allIndeed the value for nplm_overdue_contract.ALL_INDEED
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAllIndeed(Integer allIndeed) {
        this.allIndeed = allIndeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.CURRENT_REPAY
     *
     * @return the value of nplm_overdue_contract.CURRENT_REPAY
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getCurrentRepay() {
        return currentRepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.CURRENT_REPAY
     *
     * @param currentRepay the value for nplm_overdue_contract.CURRENT_REPAY
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setCurrentRepay(Integer currentRepay) {
        this.currentRepay = currentRepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.ALL_REPAYMENT_AMOUNT
     *
     * @return the value of nplm_overdue_contract.ALL_REPAYMENT_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getAllRepaymentAmount() {
        return allRepaymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.ALL_REPAYMENT_AMOUNT
     *
     * @param allRepaymentAmount the value for nplm_overdue_contract.ALL_REPAYMENT_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAllRepaymentAmount(Integer allRepaymentAmount) {
        this.allRepaymentAmount = allRepaymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.FIRST_DATE
     *
     * @return the value of nplm_overdue_contract.FIRST_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getFirstDate() {
        return firstDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.FIRST_DATE
     *
     * @param firstDate the value for nplm_overdue_contract.FIRST_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setFirstDate(String firstDate) {
        this.firstDate = firstDate == null ? null : firstDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.START_DATE
     *
     * @return the value of nplm_overdue_contract.START_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.START_DATE
     *
     * @param startDate the value for nplm_overdue_contract.START_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.SERIAL_START_DATE
     *
     * @return the value of nplm_overdue_contract.SERIAL_START_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getSerialStartDate() {
        return serialStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.SERIAL_START_DATE
     *
     * @param serialStartDate the value for nplm_overdue_contract.SERIAL_START_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setSerialStartDate(String serialStartDate) {
        this.serialStartDate = serialStartDate == null ? null : serialStartDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.OVERDUE_HISTORY
     *
     * @return the value of nplm_overdue_contract.OVERDUE_HISTORY
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getOverdueHistory() {
        return overdueHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.OVERDUE_HISTORY
     *
     * @param overdueHistory the value for nplm_overdue_contract.OVERDUE_HISTORY
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setOverdueHistory(String overdueHistory) {
        this.overdueHistory = overdueHistory == null ? null : overdueHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.COMPUTE_DATE
     *
     * @return the value of nplm_overdue_contract.COMPUTE_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getComputeDate() {
        return computeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.COMPUTE_DATE
     *
     * @param computeDate the value for nplm_overdue_contract.COMPUTE_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setComputeDate(String computeDate) {
        this.computeDate = computeDate == null ? null : computeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.CREATOR
     *
     * @return the value of nplm_overdue_contract.CREATOR
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.CREATOR
     *
     * @param creator the value for nplm_overdue_contract.CREATOR
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.CREATE_TIME
     *
     * @return the value of nplm_overdue_contract.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.CREATE_TIME
     *
     * @param createTime the value for nplm_overdue_contract.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.UPDATER
     *
     * @return the value of nplm_overdue_contract.UPDATER
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.UPDATER
     *
     * @param updater the value for nplm_overdue_contract.UPDATER
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.UPDATE_TIME
     *
     * @return the value of nplm_overdue_contract.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.UPDATE_TIME
     *
     * @param updateTime the value for nplm_overdue_contract.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_overdue_contract.UPDATE_TYPE
     *
     * @return the value of nplm_overdue_contract.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getUpdateType() {
        return updateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_overdue_contract.UPDATE_TYPE
     *
     * @param updateType the value for nplm_overdue_contract.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setUpdateType(String updateType) {
        this.updateType = updateType == null ? null : updateType.trim();
    }
}