package com.atguigu.finance.bean;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;

public class NplmRepaymentRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Id
    @Column
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.BUSINESS_REQUEST_ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer businessRequestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.LOAN_CONTRACT_NUM
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer loanContractNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.REPAYMENT_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Date repaymentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.OVERDUE_DAYS
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer overdueDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.OVERDUE_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer overdueAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.REPAYMENT_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer repaymentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.SUCCESS_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer successAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.STATUS
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.REMARK
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.SPECIAL_CODE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String specialCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.SORT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.data_create_type
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String dataCreateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.RESERVE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Date reserveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.CREATOR
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.UPDATER
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.ACCOUNT_NAME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.ACCT_IDEN_TYPE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String acctIdenType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.ACCT_IDEN_NUM
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String acctIdenNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.ACCOUNT_NO
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.ACCOUNT_TYPE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.ACCOUNT_BANKID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String accountBankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.ACCOUNT_BRANCH_NO
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String accountBranchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.ACCOUNT_BANK_NAME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String accountBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.PUBLIC_PRIVATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String publicPrivate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.ACT_PROVINCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String actProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.ACCOUNT_CITY
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String accountCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_record.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String updateType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.ID
     *
     * @return the value of nplm_repayment_record.ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.ID
     *
     * @param id the value for nplm_repayment_record.ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.BUSINESS_REQUEST_ID
     *
     * @return the value of nplm_repayment_record.BUSINESS_REQUEST_ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getBusinessRequestId() {
        return businessRequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.BUSINESS_REQUEST_ID
     *
     * @param businessRequestId the value for nplm_repayment_record.BUSINESS_REQUEST_ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setBusinessRequestId(Integer businessRequestId) {
        this.businessRequestId = businessRequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.LOAN_CONTRACT_NUM
     *
     * @return the value of nplm_repayment_record.LOAN_CONTRACT_NUM
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getLoanContractNum() {
        return loanContractNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.LOAN_CONTRACT_NUM
     *
     * @param loanContractNum the value for nplm_repayment_record.LOAN_CONTRACT_NUM
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setLoanContractNum(Integer loanContractNum) {
        this.loanContractNum = loanContractNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.REPAYMENT_DATE
     *
     * @return the value of nplm_repayment_record.REPAYMENT_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Date getRepaymentDate() {
        return repaymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.REPAYMENT_DATE
     *
     * @param repaymentDate the value for nplm_repayment_record.REPAYMENT_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setRepaymentDate(Date repaymentDate) {
        this.repaymentDate = repaymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.OVERDUE_DAYS
     *
     * @return the value of nplm_repayment_record.OVERDUE_DAYS
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getOverdueDays() {
        return overdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.OVERDUE_DAYS
     *
     * @param overdueDays the value for nplm_repayment_record.OVERDUE_DAYS
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setOverdueDays(Integer overdueDays) {
        this.overdueDays = overdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.OVERDUE_AMOUNT
     *
     * @return the value of nplm_repayment_record.OVERDUE_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getOverdueAmount() {
        return overdueAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.OVERDUE_AMOUNT
     *
     * @param overdueAmount the value for nplm_repayment_record.OVERDUE_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setOverdueAmount(Integer overdueAmount) {
        this.overdueAmount = overdueAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.REPAYMENT_AMOUNT
     *
     * @return the value of nplm_repayment_record.REPAYMENT_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getRepaymentAmount() {
        return repaymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.REPAYMENT_AMOUNT
     *
     * @param repaymentAmount the value for nplm_repayment_record.REPAYMENT_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setRepaymentAmount(Integer repaymentAmount) {
        this.repaymentAmount = repaymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.SUCCESS_AMOUNT
     *
     * @return the value of nplm_repayment_record.SUCCESS_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getSuccessAmount() {
        return successAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.SUCCESS_AMOUNT
     *
     * @param successAmount the value for nplm_repayment_record.SUCCESS_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setSuccessAmount(Integer successAmount) {
        this.successAmount = successAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.STATUS
     *
     * @return the value of nplm_repayment_record.STATUS
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.STATUS
     *
     * @param status the value for nplm_repayment_record.STATUS
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.REMARK
     *
     * @return the value of nplm_repayment_record.REMARK
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.REMARK
     *
     * @param remark the value for nplm_repayment_record.REMARK
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.SPECIAL_CODE
     *
     * @return the value of nplm_repayment_record.SPECIAL_CODE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getSpecialCode() {
        return specialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.SPECIAL_CODE
     *
     * @param specialCode the value for nplm_repayment_record.SPECIAL_CODE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setSpecialCode(String specialCode) {
        this.specialCode = specialCode == null ? null : specialCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.SORT
     *
     * @return the value of nplm_repayment_record.SORT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.SORT
     *
     * @param sort the value for nplm_repayment_record.SORT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.data_create_type
     *
     * @return the value of nplm_repayment_record.data_create_type
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getDataCreateType() {
        return dataCreateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.data_create_type
     *
     * @param dataCreateType the value for nplm_repayment_record.data_create_type
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setDataCreateType(String dataCreateType) {
        this.dataCreateType = dataCreateType == null ? null : dataCreateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.RESERVE_TIME
     *
     * @return the value of nplm_repayment_record.RESERVE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Date getReserveTime() {
        return reserveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.RESERVE_TIME
     *
     * @param reserveTime the value for nplm_repayment_record.RESERVE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setReserveTime(Date reserveTime) {
        this.reserveTime = reserveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.CREATOR
     *
     * @return the value of nplm_repayment_record.CREATOR
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.CREATOR
     *
     * @param creator the value for nplm_repayment_record.CREATOR
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.CREATE_TIME
     *
     * @return the value of nplm_repayment_record.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.CREATE_TIME
     *
     * @param createTime the value for nplm_repayment_record.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.UPDATER
     *
     * @return the value of nplm_repayment_record.UPDATER
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.UPDATER
     *
     * @param updater the value for nplm_repayment_record.UPDATER
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.UPDATE_TIME
     *
     * @return the value of nplm_repayment_record.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.UPDATE_TIME
     *
     * @param updateTime the value for nplm_repayment_record.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.ACCOUNT_NAME
     *
     * @return the value of nplm_repayment_record.ACCOUNT_NAME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.ACCOUNT_NAME
     *
     * @param accountName the value for nplm_repayment_record.ACCOUNT_NAME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.ACCT_IDEN_TYPE
     *
     * @return the value of nplm_repayment_record.ACCT_IDEN_TYPE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getAcctIdenType() {
        return acctIdenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.ACCT_IDEN_TYPE
     *
     * @param acctIdenType the value for nplm_repayment_record.ACCT_IDEN_TYPE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAcctIdenType(String acctIdenType) {
        this.acctIdenType = acctIdenType == null ? null : acctIdenType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.ACCT_IDEN_NUM
     *
     * @return the value of nplm_repayment_record.ACCT_IDEN_NUM
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getAcctIdenNum() {
        return acctIdenNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.ACCT_IDEN_NUM
     *
     * @param acctIdenNum the value for nplm_repayment_record.ACCT_IDEN_NUM
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAcctIdenNum(String acctIdenNum) {
        this.acctIdenNum = acctIdenNum == null ? null : acctIdenNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.ACCOUNT_NO
     *
     * @return the value of nplm_repayment_record.ACCOUNT_NO
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.ACCOUNT_NO
     *
     * @param accountNo the value for nplm_repayment_record.ACCOUNT_NO
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo == null ? null : accountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.ACCOUNT_TYPE
     *
     * @return the value of nplm_repayment_record.ACCOUNT_TYPE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.ACCOUNT_TYPE
     *
     * @param accountType the value for nplm_repayment_record.ACCOUNT_TYPE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.ACCOUNT_BANKID
     *
     * @return the value of nplm_repayment_record.ACCOUNT_BANKID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getAccountBankid() {
        return accountBankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.ACCOUNT_BANKID
     *
     * @param accountBankid the value for nplm_repayment_record.ACCOUNT_BANKID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAccountBankid(String accountBankid) {
        this.accountBankid = accountBankid == null ? null : accountBankid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.ACCOUNT_BRANCH_NO
     *
     * @return the value of nplm_repayment_record.ACCOUNT_BRANCH_NO
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getAccountBranchNo() {
        return accountBranchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.ACCOUNT_BRANCH_NO
     *
     * @param accountBranchNo the value for nplm_repayment_record.ACCOUNT_BRANCH_NO
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAccountBranchNo(String accountBranchNo) {
        this.accountBranchNo = accountBranchNo == null ? null : accountBranchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.ACCOUNT_BANK_NAME
     *
     * @return the value of nplm_repayment_record.ACCOUNT_BANK_NAME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getAccountBankName() {
        return accountBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.ACCOUNT_BANK_NAME
     *
     * @param accountBankName the value for nplm_repayment_record.ACCOUNT_BANK_NAME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAccountBankName(String accountBankName) {
        this.accountBankName = accountBankName == null ? null : accountBankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.PUBLIC_PRIVATE
     *
     * @return the value of nplm_repayment_record.PUBLIC_PRIVATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getPublicPrivate() {
        return publicPrivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.PUBLIC_PRIVATE
     *
     * @param publicPrivate the value for nplm_repayment_record.PUBLIC_PRIVATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setPublicPrivate(String publicPrivate) {
        this.publicPrivate = publicPrivate == null ? null : publicPrivate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.ACT_PROVINCE
     *
     * @return the value of nplm_repayment_record.ACT_PROVINCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getActProvince() {
        return actProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.ACT_PROVINCE
     *
     * @param actProvince the value for nplm_repayment_record.ACT_PROVINCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setActProvince(String actProvince) {
        this.actProvince = actProvince == null ? null : actProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.ACCOUNT_CITY
     *
     * @return the value of nplm_repayment_record.ACCOUNT_CITY
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getAccountCity() {
        return accountCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.ACCOUNT_CITY
     *
     * @param accountCity the value for nplm_repayment_record.ACCOUNT_CITY
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAccountCity(String accountCity) {
        this.accountCity = accountCity == null ? null : accountCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_record.UPDATE_TYPE
     *
     * @return the value of nplm_repayment_record.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getUpdateType() {
        return updateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_record.UPDATE_TYPE
     *
     * @param updateType the value for nplm_repayment_record.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setUpdateType(String updateType) {
        this.updateType = updateType == null ? null : updateType.trim();
    }
}