package com.atguigu.finance.bean;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;

public class NplmRepaymentDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Id
    @Column
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.REPAYMENT_PLAN_ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer repaymentPlanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.REPAYMENT_RECORD_ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer repaymentRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.BUSINESS_REQUEST_ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer businessRequestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.LOAN_CONTRACT_NUM
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer loanContractNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.REPAYMENT_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Date repaymentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.INSTALMENT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer instalment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.SHOULD_CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer shouldCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.SHOULD_INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer shouldInterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.SHOULD_INST_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer shouldInstFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.SHOULD_AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer shouldAmerce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.SHOULD_FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer shouldForfeit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.should_penalty
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer shouldPenalty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.should_change_fee
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer shouldChangeFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.SHOULD_OTHER_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer shouldOtherFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.SHOULD_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer shouldAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.INDEED_CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer indeedCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.INDEED_INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer indeedInterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.INDEED_INST_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer indeedInstFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.INDEED_AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer indeedAmerce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.INDEED_FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer indeedForfeit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.indeed_penalty
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer indeedPenalty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.indeed_change_fee
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer indeedChangeFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.indeed_OTHER_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer indeedOtherFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.INDEED_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer indeedAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.STATUS
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.reduce_CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer reduceCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.reduce_INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer reduceInterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.reduce_AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer reduceAmerce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.reduce_FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer reduceForfeit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.reduce_penalty
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer reducePenalty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.reduce_INST_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer reduceInstFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.reduce_PRE_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer reducePreFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.reduce_OTHER_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer reduceOtherFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.data_create_type
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String dataCreateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.REMARK
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.SPECIAL_CODE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String specialCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.SORT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.CREATOR
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.UPDATER
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_detail.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String updateType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.ID
     *
     * @return the value of nplm_repayment_detail.ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.ID
     *
     * @param id the value for nplm_repayment_detail.ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.REPAYMENT_PLAN_ID
     *
     * @return the value of nplm_repayment_detail.REPAYMENT_PLAN_ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getRepaymentPlanId() {
        return repaymentPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.REPAYMENT_PLAN_ID
     *
     * @param repaymentPlanId the value for nplm_repayment_detail.REPAYMENT_PLAN_ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setRepaymentPlanId(Integer repaymentPlanId) {
        this.repaymentPlanId = repaymentPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.REPAYMENT_RECORD_ID
     *
     * @return the value of nplm_repayment_detail.REPAYMENT_RECORD_ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getRepaymentRecordId() {
        return repaymentRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.REPAYMENT_RECORD_ID
     *
     * @param repaymentRecordId the value for nplm_repayment_detail.REPAYMENT_RECORD_ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setRepaymentRecordId(Integer repaymentRecordId) {
        this.repaymentRecordId = repaymentRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.BUSINESS_REQUEST_ID
     *
     * @return the value of nplm_repayment_detail.BUSINESS_REQUEST_ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getBusinessRequestId() {
        return businessRequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.BUSINESS_REQUEST_ID
     *
     * @param businessRequestId the value for nplm_repayment_detail.BUSINESS_REQUEST_ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setBusinessRequestId(Integer businessRequestId) {
        this.businessRequestId = businessRequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.LOAN_CONTRACT_NUM
     *
     * @return the value of nplm_repayment_detail.LOAN_CONTRACT_NUM
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getLoanContractNum() {
        return loanContractNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.LOAN_CONTRACT_NUM
     *
     * @param loanContractNum the value for nplm_repayment_detail.LOAN_CONTRACT_NUM
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setLoanContractNum(Integer loanContractNum) {
        this.loanContractNum = loanContractNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.REPAYMENT_DATE
     *
     * @return the value of nplm_repayment_detail.REPAYMENT_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Date getRepaymentDate() {
        return repaymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.REPAYMENT_DATE
     *
     * @param repaymentDate the value for nplm_repayment_detail.REPAYMENT_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setRepaymentDate(Date repaymentDate) {
        this.repaymentDate = repaymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.INSTALMENT
     *
     * @return the value of nplm_repayment_detail.INSTALMENT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getInstalment() {
        return instalment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.INSTALMENT
     *
     * @param instalment the value for nplm_repayment_detail.INSTALMENT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setInstalment(Integer instalment) {
        this.instalment = instalment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.SHOULD_CAPITAL
     *
     * @return the value of nplm_repayment_detail.SHOULD_CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getShouldCapital() {
        return shouldCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.SHOULD_CAPITAL
     *
     * @param shouldCapital the value for nplm_repayment_detail.SHOULD_CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setShouldCapital(Integer shouldCapital) {
        this.shouldCapital = shouldCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.SHOULD_INTEREST
     *
     * @return the value of nplm_repayment_detail.SHOULD_INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getShouldInterest() {
        return shouldInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.SHOULD_INTEREST
     *
     * @param shouldInterest the value for nplm_repayment_detail.SHOULD_INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setShouldInterest(Integer shouldInterest) {
        this.shouldInterest = shouldInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.SHOULD_INST_FEE
     *
     * @return the value of nplm_repayment_detail.SHOULD_INST_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getShouldInstFee() {
        return shouldInstFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.SHOULD_INST_FEE
     *
     * @param shouldInstFee the value for nplm_repayment_detail.SHOULD_INST_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setShouldInstFee(Integer shouldInstFee) {
        this.shouldInstFee = shouldInstFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.SHOULD_AMERCE
     *
     * @return the value of nplm_repayment_detail.SHOULD_AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getShouldAmerce() {
        return shouldAmerce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.SHOULD_AMERCE
     *
     * @param shouldAmerce the value for nplm_repayment_detail.SHOULD_AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setShouldAmerce(Integer shouldAmerce) {
        this.shouldAmerce = shouldAmerce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.SHOULD_FORFEIT
     *
     * @return the value of nplm_repayment_detail.SHOULD_FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getShouldForfeit() {
        return shouldForfeit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.SHOULD_FORFEIT
     *
     * @param shouldForfeit the value for nplm_repayment_detail.SHOULD_FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setShouldForfeit(Integer shouldForfeit) {
        this.shouldForfeit = shouldForfeit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.should_penalty
     *
     * @return the value of nplm_repayment_detail.should_penalty
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getShouldPenalty() {
        return shouldPenalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.should_penalty
     *
     * @param shouldPenalty the value for nplm_repayment_detail.should_penalty
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setShouldPenalty(Integer shouldPenalty) {
        this.shouldPenalty = shouldPenalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.should_change_fee
     *
     * @return the value of nplm_repayment_detail.should_change_fee
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getShouldChangeFee() {
        return shouldChangeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.should_change_fee
     *
     * @param shouldChangeFee the value for nplm_repayment_detail.should_change_fee
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setShouldChangeFee(Integer shouldChangeFee) {
        this.shouldChangeFee = shouldChangeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.SHOULD_OTHER_FEE
     *
     * @return the value of nplm_repayment_detail.SHOULD_OTHER_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getShouldOtherFee() {
        return shouldOtherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.SHOULD_OTHER_FEE
     *
     * @param shouldOtherFee the value for nplm_repayment_detail.SHOULD_OTHER_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setShouldOtherFee(Integer shouldOtherFee) {
        this.shouldOtherFee = shouldOtherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.SHOULD_AMOUNT
     *
     * @return the value of nplm_repayment_detail.SHOULD_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getShouldAmount() {
        return shouldAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.SHOULD_AMOUNT
     *
     * @param shouldAmount the value for nplm_repayment_detail.SHOULD_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setShouldAmount(Integer shouldAmount) {
        this.shouldAmount = shouldAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.INDEED_CAPITAL
     *
     * @return the value of nplm_repayment_detail.INDEED_CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getIndeedCapital() {
        return indeedCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.INDEED_CAPITAL
     *
     * @param indeedCapital the value for nplm_repayment_detail.INDEED_CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIndeedCapital(Integer indeedCapital) {
        this.indeedCapital = indeedCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.INDEED_INTEREST
     *
     * @return the value of nplm_repayment_detail.INDEED_INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getIndeedInterest() {
        return indeedInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.INDEED_INTEREST
     *
     * @param indeedInterest the value for nplm_repayment_detail.INDEED_INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIndeedInterest(Integer indeedInterest) {
        this.indeedInterest = indeedInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.INDEED_INST_FEE
     *
     * @return the value of nplm_repayment_detail.INDEED_INST_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getIndeedInstFee() {
        return indeedInstFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.INDEED_INST_FEE
     *
     * @param indeedInstFee the value for nplm_repayment_detail.INDEED_INST_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIndeedInstFee(Integer indeedInstFee) {
        this.indeedInstFee = indeedInstFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.INDEED_AMERCE
     *
     * @return the value of nplm_repayment_detail.INDEED_AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getIndeedAmerce() {
        return indeedAmerce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.INDEED_AMERCE
     *
     * @param indeedAmerce the value for nplm_repayment_detail.INDEED_AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIndeedAmerce(Integer indeedAmerce) {
        this.indeedAmerce = indeedAmerce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.INDEED_FORFEIT
     *
     * @return the value of nplm_repayment_detail.INDEED_FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getIndeedForfeit() {
        return indeedForfeit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.INDEED_FORFEIT
     *
     * @param indeedForfeit the value for nplm_repayment_detail.INDEED_FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIndeedForfeit(Integer indeedForfeit) {
        this.indeedForfeit = indeedForfeit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.indeed_penalty
     *
     * @return the value of nplm_repayment_detail.indeed_penalty
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getIndeedPenalty() {
        return indeedPenalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.indeed_penalty
     *
     * @param indeedPenalty the value for nplm_repayment_detail.indeed_penalty
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIndeedPenalty(Integer indeedPenalty) {
        this.indeedPenalty = indeedPenalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.indeed_change_fee
     *
     * @return the value of nplm_repayment_detail.indeed_change_fee
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getIndeedChangeFee() {
        return indeedChangeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.indeed_change_fee
     *
     * @param indeedChangeFee the value for nplm_repayment_detail.indeed_change_fee
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIndeedChangeFee(Integer indeedChangeFee) {
        this.indeedChangeFee = indeedChangeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.indeed_OTHER_FEE
     *
     * @return the value of nplm_repayment_detail.indeed_OTHER_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getIndeedOtherFee() {
        return indeedOtherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.indeed_OTHER_FEE
     *
     * @param indeedOtherFee the value for nplm_repayment_detail.indeed_OTHER_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIndeedOtherFee(Integer indeedOtherFee) {
        this.indeedOtherFee = indeedOtherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.INDEED_AMOUNT
     *
     * @return the value of nplm_repayment_detail.INDEED_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getIndeedAmount() {
        return indeedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.INDEED_AMOUNT
     *
     * @param indeedAmount the value for nplm_repayment_detail.INDEED_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIndeedAmount(Integer indeedAmount) {
        this.indeedAmount = indeedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.STATUS
     *
     * @return the value of nplm_repayment_detail.STATUS
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.STATUS
     *
     * @param status the value for nplm_repayment_detail.STATUS
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.reduce_CAPITAL
     *
     * @return the value of nplm_repayment_detail.reduce_CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getReduceCapital() {
        return reduceCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.reduce_CAPITAL
     *
     * @param reduceCapital the value for nplm_repayment_detail.reduce_CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setReduceCapital(Integer reduceCapital) {
        this.reduceCapital = reduceCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.reduce_INTEREST
     *
     * @return the value of nplm_repayment_detail.reduce_INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getReduceInterest() {
        return reduceInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.reduce_INTEREST
     *
     * @param reduceInterest the value for nplm_repayment_detail.reduce_INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setReduceInterest(Integer reduceInterest) {
        this.reduceInterest = reduceInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.reduce_AMERCE
     *
     * @return the value of nplm_repayment_detail.reduce_AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getReduceAmerce() {
        return reduceAmerce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.reduce_AMERCE
     *
     * @param reduceAmerce the value for nplm_repayment_detail.reduce_AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setReduceAmerce(Integer reduceAmerce) {
        this.reduceAmerce = reduceAmerce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.reduce_FORFEIT
     *
     * @return the value of nplm_repayment_detail.reduce_FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getReduceForfeit() {
        return reduceForfeit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.reduce_FORFEIT
     *
     * @param reduceForfeit the value for nplm_repayment_detail.reduce_FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setReduceForfeit(Integer reduceForfeit) {
        this.reduceForfeit = reduceForfeit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.reduce_penalty
     *
     * @return the value of nplm_repayment_detail.reduce_penalty
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getReducePenalty() {
        return reducePenalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.reduce_penalty
     *
     * @param reducePenalty the value for nplm_repayment_detail.reduce_penalty
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setReducePenalty(Integer reducePenalty) {
        this.reducePenalty = reducePenalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.reduce_INST_FEE
     *
     * @return the value of nplm_repayment_detail.reduce_INST_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getReduceInstFee() {
        return reduceInstFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.reduce_INST_FEE
     *
     * @param reduceInstFee the value for nplm_repayment_detail.reduce_INST_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setReduceInstFee(Integer reduceInstFee) {
        this.reduceInstFee = reduceInstFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.reduce_PRE_FEE
     *
     * @return the value of nplm_repayment_detail.reduce_PRE_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getReducePreFee() {
        return reducePreFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.reduce_PRE_FEE
     *
     * @param reducePreFee the value for nplm_repayment_detail.reduce_PRE_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setReducePreFee(Integer reducePreFee) {
        this.reducePreFee = reducePreFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.reduce_OTHER_FEE
     *
     * @return the value of nplm_repayment_detail.reduce_OTHER_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getReduceOtherFee() {
        return reduceOtherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.reduce_OTHER_FEE
     *
     * @param reduceOtherFee the value for nplm_repayment_detail.reduce_OTHER_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setReduceOtherFee(Integer reduceOtherFee) {
        this.reduceOtherFee = reduceOtherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.data_create_type
     *
     * @return the value of nplm_repayment_detail.data_create_type
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getDataCreateType() {
        return dataCreateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.data_create_type
     *
     * @param dataCreateType the value for nplm_repayment_detail.data_create_type
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setDataCreateType(String dataCreateType) {
        this.dataCreateType = dataCreateType == null ? null : dataCreateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.REMARK
     *
     * @return the value of nplm_repayment_detail.REMARK
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.REMARK
     *
     * @param remark the value for nplm_repayment_detail.REMARK
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.SPECIAL_CODE
     *
     * @return the value of nplm_repayment_detail.SPECIAL_CODE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getSpecialCode() {
        return specialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.SPECIAL_CODE
     *
     * @param specialCode the value for nplm_repayment_detail.SPECIAL_CODE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setSpecialCode(String specialCode) {
        this.specialCode = specialCode == null ? null : specialCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.SORT
     *
     * @return the value of nplm_repayment_detail.SORT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.SORT
     *
     * @param sort the value for nplm_repayment_detail.SORT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.CREATOR
     *
     * @return the value of nplm_repayment_detail.CREATOR
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.CREATOR
     *
     * @param creator the value for nplm_repayment_detail.CREATOR
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.CREATE_TIME
     *
     * @return the value of nplm_repayment_detail.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.CREATE_TIME
     *
     * @param createTime the value for nplm_repayment_detail.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.UPDATER
     *
     * @return the value of nplm_repayment_detail.UPDATER
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.UPDATER
     *
     * @param updater the value for nplm_repayment_detail.UPDATER
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.UPDATE_TIME
     *
     * @return the value of nplm_repayment_detail.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.UPDATE_TIME
     *
     * @param updateTime the value for nplm_repayment_detail.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_detail.UPDATE_TYPE
     *
     * @return the value of nplm_repayment_detail.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getUpdateType() {
        return updateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_detail.UPDATE_TYPE
     *
     * @param updateType the value for nplm_repayment_detail.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setUpdateType(String updateType) {
        this.updateType = updateType == null ? null : updateType.trim();
    }
}