package com.atguigu.finance.bean;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;

public class NplmLoanContract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Id
    @Column
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.LOAN_CONTRACT_NUM
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String loanContractNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.borrower_id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String borrowerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.ECIF_ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String ecifId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.pro_CATEGORY_CODE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String proCategoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.pro_CATEGORY_NAME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String proCategoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.PRODUCT_INFO_ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer productInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.LOAN_INSTALMENTS
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer loanInstalments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.LOAN_INSTALMENT_UNIT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String loanInstalmentUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.LOAN_AMOUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer loanAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.PRE_FEE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer preFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.PUT_AMOUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer putAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.CREDIT_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String creditType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.PAY_MOD
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String payMod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.REPAY_WAY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String repayWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.LOAN_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String loanType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.SALE_DEPARTMENT_ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer saleDepartmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.REPAY_ACCOUNT_NAME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String repayAccountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.REPAY_ACCT_IDEN_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String repayAcctIdenType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.REPAY_ACCT_IDEN_NUM
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String repayAcctIdenNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.REPAY_ACCOUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String repayAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.REPAY_ACCOUNT_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String repayAccountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.REPAY_ACCOUNT_BANKID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String repayAccountBankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.REPAY_ACT_BRANCH_NO
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String repayActBranchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.REPAY_ACCOUNT_BANK_NAME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String repayAccountBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.PUBLIC_PRIVATE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String publicPrivate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.REPAY_ACT_PROVINCE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String repayActProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.REPAY_ACCOUNT_CITY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String repayAccountCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.POS_STATUS
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String posStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.START_DATE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.END_DATE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.CONTRACT_SOURCE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String contractSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.REPAY_BALANCE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer repayBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.CONTRACT_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String contractType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.CREATOR
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.UPDATER
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.REMARK
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.CYCLE_CREDIT_ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String cycleCreditId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_loan_contract.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String updateType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.ID
     *
     * @return the value of nplm_loan_contract.ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.ID
     *
     * @param id the value for nplm_loan_contract.ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.LOAN_CONTRACT_NUM
     *
     * @return the value of nplm_loan_contract.LOAN_CONTRACT_NUM
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getLoanContractNum() {
        return loanContractNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.LOAN_CONTRACT_NUM
     *
     * @param loanContractNum the value for nplm_loan_contract.LOAN_CONTRACT_NUM
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setLoanContractNum(String loanContractNum) {
        this.loanContractNum = loanContractNum == null ? null : loanContractNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.borrower_id
     *
     * @return the value of nplm_loan_contract.borrower_id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getBorrowerId() {
        return borrowerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.borrower_id
     *
     * @param borrowerId the value for nplm_loan_contract.borrower_id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setBorrowerId(String borrowerId) {
        this.borrowerId = borrowerId == null ? null : borrowerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.ECIF_ID
     *
     * @return the value of nplm_loan_contract.ECIF_ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getEcifId() {
        return ecifId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.ECIF_ID
     *
     * @param ecifId the value for nplm_loan_contract.ECIF_ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setEcifId(String ecifId) {
        this.ecifId = ecifId == null ? null : ecifId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.pro_CATEGORY_CODE
     *
     * @return the value of nplm_loan_contract.pro_CATEGORY_CODE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getProCategoryCode() {
        return proCategoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.pro_CATEGORY_CODE
     *
     * @param proCategoryCode the value for nplm_loan_contract.pro_CATEGORY_CODE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setProCategoryCode(String proCategoryCode) {
        this.proCategoryCode = proCategoryCode == null ? null : proCategoryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.pro_CATEGORY_NAME
     *
     * @return the value of nplm_loan_contract.pro_CATEGORY_NAME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getProCategoryName() {
        return proCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.pro_CATEGORY_NAME
     *
     * @param proCategoryName the value for nplm_loan_contract.pro_CATEGORY_NAME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setProCategoryName(String proCategoryName) {
        this.proCategoryName = proCategoryName == null ? null : proCategoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.PRODUCT_INFO_ID
     *
     * @return the value of nplm_loan_contract.PRODUCT_INFO_ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getProductInfoId() {
        return productInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.PRODUCT_INFO_ID
     *
     * @param productInfoId the value for nplm_loan_contract.PRODUCT_INFO_ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setProductInfoId(Integer productInfoId) {
        this.productInfoId = productInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.LOAN_INSTALMENTS
     *
     * @return the value of nplm_loan_contract.LOAN_INSTALMENTS
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getLoanInstalments() {
        return loanInstalments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.LOAN_INSTALMENTS
     *
     * @param loanInstalments the value for nplm_loan_contract.LOAN_INSTALMENTS
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setLoanInstalments(Integer loanInstalments) {
        this.loanInstalments = loanInstalments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.LOAN_INSTALMENT_UNIT
     *
     * @return the value of nplm_loan_contract.LOAN_INSTALMENT_UNIT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getLoanInstalmentUnit() {
        return loanInstalmentUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.LOAN_INSTALMENT_UNIT
     *
     * @param loanInstalmentUnit the value for nplm_loan_contract.LOAN_INSTALMENT_UNIT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setLoanInstalmentUnit(String loanInstalmentUnit) {
        this.loanInstalmentUnit = loanInstalmentUnit == null ? null : loanInstalmentUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.LOAN_AMOUNT
     *
     * @return the value of nplm_loan_contract.LOAN_AMOUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getLoanAmount() {
        return loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.LOAN_AMOUNT
     *
     * @param loanAmount the value for nplm_loan_contract.LOAN_AMOUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setLoanAmount(Integer loanAmount) {
        this.loanAmount = loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.PRE_FEE
     *
     * @return the value of nplm_loan_contract.PRE_FEE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getPreFee() {
        return preFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.PRE_FEE
     *
     * @param preFee the value for nplm_loan_contract.PRE_FEE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setPreFee(Integer preFee) {
        this.preFee = preFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.PUT_AMOUNT
     *
     * @return the value of nplm_loan_contract.PUT_AMOUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getPutAmount() {
        return putAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.PUT_AMOUNT
     *
     * @param putAmount the value for nplm_loan_contract.PUT_AMOUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setPutAmount(Integer putAmount) {
        this.putAmount = putAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.CREDIT_TYPE
     *
     * @return the value of nplm_loan_contract.CREDIT_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getCreditType() {
        return creditType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.CREDIT_TYPE
     *
     * @param creditType the value for nplm_loan_contract.CREDIT_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setCreditType(String creditType) {
        this.creditType = creditType == null ? null : creditType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.PAY_MOD
     *
     * @return the value of nplm_loan_contract.PAY_MOD
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getPayMod() {
        return payMod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.PAY_MOD
     *
     * @param payMod the value for nplm_loan_contract.PAY_MOD
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setPayMod(String payMod) {
        this.payMod = payMod == null ? null : payMod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.REPAY_WAY
     *
     * @return the value of nplm_loan_contract.REPAY_WAY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getRepayWay() {
        return repayWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.REPAY_WAY
     *
     * @param repayWay the value for nplm_loan_contract.REPAY_WAY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setRepayWay(String repayWay) {
        this.repayWay = repayWay == null ? null : repayWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.LOAN_TYPE
     *
     * @return the value of nplm_loan_contract.LOAN_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getLoanType() {
        return loanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.LOAN_TYPE
     *
     * @param loanType the value for nplm_loan_contract.LOAN_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setLoanType(String loanType) {
        this.loanType = loanType == null ? null : loanType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.SALE_DEPARTMENT_ID
     *
     * @return the value of nplm_loan_contract.SALE_DEPARTMENT_ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getSaleDepartmentId() {
        return saleDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.SALE_DEPARTMENT_ID
     *
     * @param saleDepartmentId the value for nplm_loan_contract.SALE_DEPARTMENT_ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setSaleDepartmentId(Integer saleDepartmentId) {
        this.saleDepartmentId = saleDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.REPAY_ACCOUNT_NAME
     *
     * @return the value of nplm_loan_contract.REPAY_ACCOUNT_NAME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getRepayAccountName() {
        return repayAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.REPAY_ACCOUNT_NAME
     *
     * @param repayAccountName the value for nplm_loan_contract.REPAY_ACCOUNT_NAME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setRepayAccountName(String repayAccountName) {
        this.repayAccountName = repayAccountName == null ? null : repayAccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.REPAY_ACCT_IDEN_TYPE
     *
     * @return the value of nplm_loan_contract.REPAY_ACCT_IDEN_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getRepayAcctIdenType() {
        return repayAcctIdenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.REPAY_ACCT_IDEN_TYPE
     *
     * @param repayAcctIdenType the value for nplm_loan_contract.REPAY_ACCT_IDEN_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setRepayAcctIdenType(String repayAcctIdenType) {
        this.repayAcctIdenType = repayAcctIdenType == null ? null : repayAcctIdenType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.REPAY_ACCT_IDEN_NUM
     *
     * @return the value of nplm_loan_contract.REPAY_ACCT_IDEN_NUM
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getRepayAcctIdenNum() {
        return repayAcctIdenNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.REPAY_ACCT_IDEN_NUM
     *
     * @param repayAcctIdenNum the value for nplm_loan_contract.REPAY_ACCT_IDEN_NUM
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setRepayAcctIdenNum(String repayAcctIdenNum) {
        this.repayAcctIdenNum = repayAcctIdenNum == null ? null : repayAcctIdenNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.REPAY_ACCOUNT
     *
     * @return the value of nplm_loan_contract.REPAY_ACCOUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getRepayAccount() {
        return repayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.REPAY_ACCOUNT
     *
     * @param repayAccount the value for nplm_loan_contract.REPAY_ACCOUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setRepayAccount(String repayAccount) {
        this.repayAccount = repayAccount == null ? null : repayAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.REPAY_ACCOUNT_TYPE
     *
     * @return the value of nplm_loan_contract.REPAY_ACCOUNT_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getRepayAccountType() {
        return repayAccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.REPAY_ACCOUNT_TYPE
     *
     * @param repayAccountType the value for nplm_loan_contract.REPAY_ACCOUNT_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setRepayAccountType(String repayAccountType) {
        this.repayAccountType = repayAccountType == null ? null : repayAccountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.REPAY_ACCOUNT_BANKID
     *
     * @return the value of nplm_loan_contract.REPAY_ACCOUNT_BANKID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getRepayAccountBankid() {
        return repayAccountBankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.REPAY_ACCOUNT_BANKID
     *
     * @param repayAccountBankid the value for nplm_loan_contract.REPAY_ACCOUNT_BANKID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setRepayAccountBankid(String repayAccountBankid) {
        this.repayAccountBankid = repayAccountBankid == null ? null : repayAccountBankid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.REPAY_ACT_BRANCH_NO
     *
     * @return the value of nplm_loan_contract.REPAY_ACT_BRANCH_NO
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getRepayActBranchNo() {
        return repayActBranchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.REPAY_ACT_BRANCH_NO
     *
     * @param repayActBranchNo the value for nplm_loan_contract.REPAY_ACT_BRANCH_NO
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setRepayActBranchNo(String repayActBranchNo) {
        this.repayActBranchNo = repayActBranchNo == null ? null : repayActBranchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.REPAY_ACCOUNT_BANK_NAME
     *
     * @return the value of nplm_loan_contract.REPAY_ACCOUNT_BANK_NAME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getRepayAccountBankName() {
        return repayAccountBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.REPAY_ACCOUNT_BANK_NAME
     *
     * @param repayAccountBankName the value for nplm_loan_contract.REPAY_ACCOUNT_BANK_NAME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setRepayAccountBankName(String repayAccountBankName) {
        this.repayAccountBankName = repayAccountBankName == null ? null : repayAccountBankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.PUBLIC_PRIVATE
     *
     * @return the value of nplm_loan_contract.PUBLIC_PRIVATE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getPublicPrivate() {
        return publicPrivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.PUBLIC_PRIVATE
     *
     * @param publicPrivate the value for nplm_loan_contract.PUBLIC_PRIVATE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setPublicPrivate(String publicPrivate) {
        this.publicPrivate = publicPrivate == null ? null : publicPrivate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.REPAY_ACT_PROVINCE
     *
     * @return the value of nplm_loan_contract.REPAY_ACT_PROVINCE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getRepayActProvince() {
        return repayActProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.REPAY_ACT_PROVINCE
     *
     * @param repayActProvince the value for nplm_loan_contract.REPAY_ACT_PROVINCE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setRepayActProvince(String repayActProvince) {
        this.repayActProvince = repayActProvince == null ? null : repayActProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.REPAY_ACCOUNT_CITY
     *
     * @return the value of nplm_loan_contract.REPAY_ACCOUNT_CITY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getRepayAccountCity() {
        return repayAccountCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.REPAY_ACCOUNT_CITY
     *
     * @param repayAccountCity the value for nplm_loan_contract.REPAY_ACCOUNT_CITY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setRepayAccountCity(String repayAccountCity) {
        this.repayAccountCity = repayAccountCity == null ? null : repayAccountCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.POS_STATUS
     *
     * @return the value of nplm_loan_contract.POS_STATUS
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getPosStatus() {
        return posStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.POS_STATUS
     *
     * @param posStatus the value for nplm_loan_contract.POS_STATUS
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setPosStatus(String posStatus) {
        this.posStatus = posStatus == null ? null : posStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.START_DATE
     *
     * @return the value of nplm_loan_contract.START_DATE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.START_DATE
     *
     * @param startDate the value for nplm_loan_contract.START_DATE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.END_DATE
     *
     * @return the value of nplm_loan_contract.END_DATE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.END_DATE
     *
     * @param endDate the value for nplm_loan_contract.END_DATE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.CONTRACT_SOURCE
     *
     * @return the value of nplm_loan_contract.CONTRACT_SOURCE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getContractSource() {
        return contractSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.CONTRACT_SOURCE
     *
     * @param contractSource the value for nplm_loan_contract.CONTRACT_SOURCE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setContractSource(String contractSource) {
        this.contractSource = contractSource == null ? null : contractSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.REPAY_BALANCE
     *
     * @return the value of nplm_loan_contract.REPAY_BALANCE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getRepayBalance() {
        return repayBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.REPAY_BALANCE
     *
     * @param repayBalance the value for nplm_loan_contract.REPAY_BALANCE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setRepayBalance(Integer repayBalance) {
        this.repayBalance = repayBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.CONTRACT_TYPE
     *
     * @return the value of nplm_loan_contract.CONTRACT_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getContractType() {
        return contractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.CONTRACT_TYPE
     *
     * @param contractType the value for nplm_loan_contract.CONTRACT_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setContractType(String contractType) {
        this.contractType = contractType == null ? null : contractType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.CREATOR
     *
     * @return the value of nplm_loan_contract.CREATOR
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.CREATOR
     *
     * @param creator the value for nplm_loan_contract.CREATOR
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.UPDATER
     *
     * @return the value of nplm_loan_contract.UPDATER
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.UPDATER
     *
     * @param updater the value for nplm_loan_contract.UPDATER
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.CREATE_TIME
     *
     * @return the value of nplm_loan_contract.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.CREATE_TIME
     *
     * @param createTime the value for nplm_loan_contract.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.UPDATE_TIME
     *
     * @return the value of nplm_loan_contract.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.UPDATE_TIME
     *
     * @param updateTime the value for nplm_loan_contract.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.REMARK
     *
     * @return the value of nplm_loan_contract.REMARK
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.REMARK
     *
     * @param remark the value for nplm_loan_contract.REMARK
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.CYCLE_CREDIT_ID
     *
     * @return the value of nplm_loan_contract.CYCLE_CREDIT_ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getCycleCreditId() {
        return cycleCreditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.CYCLE_CREDIT_ID
     *
     * @param cycleCreditId the value for nplm_loan_contract.CYCLE_CREDIT_ID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setCycleCreditId(String cycleCreditId) {
        this.cycleCreditId = cycleCreditId == null ? null : cycleCreditId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_loan_contract.UPDATE_TYPE
     *
     * @return the value of nplm_loan_contract.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getUpdateType() {
        return updateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_loan_contract.UPDATE_TYPE
     *
     * @param updateType the value for nplm_loan_contract.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setUpdateType(String updateType) {
        this.updateType = updateType == null ? null : updateType.trim();
    }
}