package com.atguigu.finance.bean;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;

public class NplmContractAttribute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Id
    @Column
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Integer id;
    @Column
    private String ClientName;

    public String getClientName() {
        return ClientName;
    }

    public void setClientName(String clientName) {
        ClientName = clientName;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.loan_contract_id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer loanContractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.LOAN_CONTRACT_NUM
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer loanContractNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.business_type
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.is_expedited
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String isExpedited;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.sign_date
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Date signDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.sign_type
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer signType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.approve_date
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String approveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.first_repay_date
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String firstRepayDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.fee_flag
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer feeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.interest_flag
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String interestFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.interest_type
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer interestType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.grace_days
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer graceDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.irr
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer irr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.lns_rate
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer lnsRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.channel_code
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String channelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.channel_name
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.loan_officer_id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String loanOfficerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.cityID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.city
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.is_modify
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String isModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.is_scheme_modify
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String isSchemeModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.recycle_way
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer recycleWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.is_recycle_load
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String isRecycleLoad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.recycle_loan_cnt
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer recycleLoanCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.old_contract_num
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String oldContractNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.settle_amount
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer settleAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.new_contract_num
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String newContractNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.is_shorten
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String isShorten;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.is_extend
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String isExtend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.is_change_produce
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String isChangeProduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.is_overdue
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String isOverdue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.is_pay_ahead
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String isPayAhead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.is_pay_part
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String isPayPart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.purpose
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String purpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.purpose_son
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String purposeSon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.purpose_detail
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String purposeDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.is_div_account
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String isDivAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.system_type
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String systemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.high_risk
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String highRisk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.is_buyout
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String isBuyout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.fee_process_type
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String feeProcessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.student_corp_name
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String studentCorpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.settle_date
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String settleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.habit_time
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String habitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.RepayDay
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String repayday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.apply_Id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String applyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.old_Apply_Id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String oldApplyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.dept_id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.dept_name
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.CREATOR
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.UPDATER
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String updateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.FRONT_CHARGE_DISCOUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer frontChargeDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.MONTH_M_RATE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer monthMRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.HANDLE_CHARGE_RATE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer handleChargeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.LOAN_TIMES
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer loanTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.PAWN
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String pawn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.HANDLE_CHARGE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer handleCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.MONTH_CHARGE_DISCOUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer monthChargeDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.GUARANTEE_FEE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private Integer guaranteeFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.GUARANTEE_COMPANY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String guaranteeCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.def1
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String def1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.def2
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String def2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.def3
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String def3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.def4
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String def4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.def5
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String def5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.def6
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String def6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.def7
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String def7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.def8
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String def8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.def9
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String def9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_contract_attribute.def10
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    @Column
    private String def10;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.id
     *
     * @return the value of nplm_contract_attribute.id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.id
     *
     * @param id the value for nplm_contract_attribute.id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.loan_contract_id
     *
     * @return the value of nplm_contract_attribute.loan_contract_id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */

    public Integer getLoanContractId() {
        return loanContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.loan_contract_id
     *
     * @param loanContractId the value for nplm_contract_attribute.loan_contract_id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setLoanContractId(Integer loanContractId) {
        this.loanContractId = loanContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.LOAN_CONTRACT_NUM
     *
     * @return the value of nplm_contract_attribute.LOAN_CONTRACT_NUM
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getLoanContractNum() {
        return loanContractNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.LOAN_CONTRACT_NUM
     *
     * @param loanContractNum the value for nplm_contract_attribute.LOAN_CONTRACT_NUM
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setLoanContractNum(Integer loanContractNum) {
        this.loanContractNum = loanContractNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.business_type
     *
     * @return the value of nplm_contract_attribute.business_type
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.business_type
     *
     * @param businessType the value for nplm_contract_attribute.business_type
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType == null ? null : businessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.is_expedited
     *
     * @return the value of nplm_contract_attribute.is_expedited
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getIsExpedited() {
        return isExpedited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.is_expedited
     *
     * @param isExpedited the value for nplm_contract_attribute.is_expedited
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setIsExpedited(String isExpedited) {
        this.isExpedited = isExpedited == null ? null : isExpedited.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.sign_date
     *
     * @return the value of nplm_contract_attribute.sign_date
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Date getSignDate() {
        return signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.sign_date
     *
     * @param signDate the value for nplm_contract_attribute.sign_date
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setSignDate(Date signDate) {
        this.signDate = signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.sign_type
     *
     * @return the value of nplm_contract_attribute.sign_type
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.sign_type
     *
     * @param signType the value for nplm_contract_attribute.sign_type
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setSignType(Integer signType) {
        this.signType = signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.approve_date
     *
     * @return the value of nplm_contract_attribute.approve_date
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getApproveDate() {
        return approveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.approve_date
     *
     * @param approveDate the value for nplm_contract_attribute.approve_date
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setApproveDate(String approveDate) {
        this.approveDate = approveDate == null ? null : approveDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.first_repay_date
     *
     * @return the value of nplm_contract_attribute.first_repay_date
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getFirstRepayDate() {
        return firstRepayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.first_repay_date
     *
     * @param firstRepayDate the value for nplm_contract_attribute.first_repay_date
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setFirstRepayDate(String firstRepayDate) {
        this.firstRepayDate = firstRepayDate == null ? null : firstRepayDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.fee_flag
     *
     * @return the value of nplm_contract_attribute.fee_flag
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getFeeFlag() {
        return feeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.fee_flag
     *
     * @param feeFlag the value for nplm_contract_attribute.fee_flag
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setFeeFlag(Integer feeFlag) {
        this.feeFlag = feeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.interest_flag
     *
     * @return the value of nplm_contract_attribute.interest_flag
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getInterestFlag() {
        return interestFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.interest_flag
     *
     * @param interestFlag the value for nplm_contract_attribute.interest_flag
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setInterestFlag(String interestFlag) {
        this.interestFlag = interestFlag == null ? null : interestFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.interest_type
     *
     * @return the value of nplm_contract_attribute.interest_type
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getInterestType() {
        return interestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.interest_type
     *
     * @param interestType the value for nplm_contract_attribute.interest_type
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setInterestType(Integer interestType) {
        this.interestType = interestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.grace_days
     *
     * @return the value of nplm_contract_attribute.grace_days
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getGraceDays() {
        return graceDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.grace_days
     *
     * @param graceDays the value for nplm_contract_attribute.grace_days
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setGraceDays(Integer graceDays) {
        this.graceDays = graceDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.irr
     *
     * @return the value of nplm_contract_attribute.irr
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getIrr() {
        return irr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.irr
     *
     * @param irr the value for nplm_contract_attribute.irr
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setIrr(Integer irr) {
        this.irr = irr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.lns_rate
     *
     * @return the value of nplm_contract_attribute.lns_rate
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getLnsRate() {
        return lnsRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.lns_rate
     *
     * @param lnsRate the value for nplm_contract_attribute.lns_rate
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setLnsRate(Integer lnsRate) {
        this.lnsRate = lnsRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.channel_code
     *
     * @return the value of nplm_contract_attribute.channel_code
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.channel_code
     *
     * @param channelCode the value for nplm_contract_attribute.channel_code
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode == null ? null : channelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.channel_name
     *
     * @return the value of nplm_contract_attribute.channel_name
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.channel_name
     *
     * @param channelName the value for nplm_contract_attribute.channel_name
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.loan_officer_id
     *
     * @return the value of nplm_contract_attribute.loan_officer_id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getLoanOfficerId() {
        return loanOfficerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.loan_officer_id
     *
     * @param loanOfficerId the value for nplm_contract_attribute.loan_officer_id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setLoanOfficerId(String loanOfficerId) {
        this.loanOfficerId = loanOfficerId == null ? null : loanOfficerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.cityID
     *
     * @return the value of nplm_contract_attribute.cityID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.cityID
     *
     * @param cityid the value for nplm_contract_attribute.cityID
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.city
     *
     * @return the value of nplm_contract_attribute.city
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.city
     *
     * @param city the value for nplm_contract_attribute.city
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.is_modify
     *
     * @return the value of nplm_contract_attribute.is_modify
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getIsModify() {
        return isModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.is_modify
     *
     * @param isModify the value for nplm_contract_attribute.is_modify
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setIsModify(String isModify) {
        this.isModify = isModify == null ? null : isModify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.is_scheme_modify
     *
     * @return the value of nplm_contract_attribute.is_scheme_modify
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getIsSchemeModify() {
        return isSchemeModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.is_scheme_modify
     *
     * @param isSchemeModify the value for nplm_contract_attribute.is_scheme_modify
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setIsSchemeModify(String isSchemeModify) {
        this.isSchemeModify = isSchemeModify == null ? null : isSchemeModify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.recycle_way
     *
     * @return the value of nplm_contract_attribute.recycle_way
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getRecycleWay() {
        return recycleWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.recycle_way
     *
     * @param recycleWay the value for nplm_contract_attribute.recycle_way
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setRecycleWay(Integer recycleWay) {
        this.recycleWay = recycleWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.is_recycle_load
     *
     * @return the value of nplm_contract_attribute.is_recycle_load
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getIsRecycleLoad() {
        return isRecycleLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.is_recycle_load
     *
     * @param isRecycleLoad the value for nplm_contract_attribute.is_recycle_load
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setIsRecycleLoad(String isRecycleLoad) {
        this.isRecycleLoad = isRecycleLoad == null ? null : isRecycleLoad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.recycle_loan_cnt
     *
     * @return the value of nplm_contract_attribute.recycle_loan_cnt
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getRecycleLoanCnt() {
        return recycleLoanCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.recycle_loan_cnt
     *
     * @param recycleLoanCnt the value for nplm_contract_attribute.recycle_loan_cnt
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setRecycleLoanCnt(Integer recycleLoanCnt) {
        this.recycleLoanCnt = recycleLoanCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.old_contract_num
     *
     * @return the value of nplm_contract_attribute.old_contract_num
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getOldContractNum() {
        return oldContractNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.old_contract_num
     *
     * @param oldContractNum the value for nplm_contract_attribute.old_contract_num
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setOldContractNum(String oldContractNum) {
        this.oldContractNum = oldContractNum == null ? null : oldContractNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.settle_amount
     *
     * @return the value of nplm_contract_attribute.settle_amount
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getSettleAmount() {
        return settleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.settle_amount
     *
     * @param settleAmount the value for nplm_contract_attribute.settle_amount
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setSettleAmount(Integer settleAmount) {
        this.settleAmount = settleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.new_contract_num
     *
     * @return the value of nplm_contract_attribute.new_contract_num
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getNewContractNum() {
        return newContractNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.new_contract_num
     *
     * @param newContractNum the value for nplm_contract_attribute.new_contract_num
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setNewContractNum(String newContractNum) {
        this.newContractNum = newContractNum == null ? null : newContractNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.is_shorten
     *
     * @return the value of nplm_contract_attribute.is_shorten
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getIsShorten() {
        return isShorten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.is_shorten
     *
     * @param isShorten the value for nplm_contract_attribute.is_shorten
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setIsShorten(String isShorten) {
        this.isShorten = isShorten == null ? null : isShorten.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.is_extend
     *
     * @return the value of nplm_contract_attribute.is_extend
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getIsExtend() {
        return isExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.is_extend
     *
     * @param isExtend the value for nplm_contract_attribute.is_extend
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setIsExtend(String isExtend) {
        this.isExtend = isExtend == null ? null : isExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.is_change_produce
     *
     * @return the value of nplm_contract_attribute.is_change_produce
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getIsChangeProduce() {
        return isChangeProduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.is_change_produce
     *
     * @param isChangeProduce the value for nplm_contract_attribute.is_change_produce
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setIsChangeProduce(String isChangeProduce) {
        this.isChangeProduce = isChangeProduce == null ? null : isChangeProduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.is_overdue
     *
     * @return the value of nplm_contract_attribute.is_overdue
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getIsOverdue() {
        return isOverdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.is_overdue
     *
     * @param isOverdue the value for nplm_contract_attribute.is_overdue
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setIsOverdue(String isOverdue) {
        this.isOverdue = isOverdue == null ? null : isOverdue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.is_pay_ahead
     *
     * @return the value of nplm_contract_attribute.is_pay_ahead
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getIsPayAhead() {
        return isPayAhead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.is_pay_ahead
     *
     * @param isPayAhead the value for nplm_contract_attribute.is_pay_ahead
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setIsPayAhead(String isPayAhead) {
        this.isPayAhead = isPayAhead == null ? null : isPayAhead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.is_pay_part
     *
     * @return the value of nplm_contract_attribute.is_pay_part
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getIsPayPart() {
        return isPayPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.is_pay_part
     *
     * @param isPayPart the value for nplm_contract_attribute.is_pay_part
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setIsPayPart(String isPayPart) {
        this.isPayPart = isPayPart == null ? null : isPayPart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.purpose
     *
     * @return the value of nplm_contract_attribute.purpose
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.purpose
     *
     * @param purpose the value for nplm_contract_attribute.purpose
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose == null ? null : purpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.purpose_son
     *
     * @return the value of nplm_contract_attribute.purpose_son
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getPurposeSon() {
        return purposeSon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.purpose_son
     *
     * @param purposeSon the value for nplm_contract_attribute.purpose_son
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setPurposeSon(String purposeSon) {
        this.purposeSon = purposeSon == null ? null : purposeSon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.purpose_detail
     *
     * @return the value of nplm_contract_attribute.purpose_detail
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getPurposeDetail() {
        return purposeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.purpose_detail
     *
     * @param purposeDetail the value for nplm_contract_attribute.purpose_detail
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setPurposeDetail(String purposeDetail) {
        this.purposeDetail = purposeDetail == null ? null : purposeDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.is_div_account
     *
     * @return the value of nplm_contract_attribute.is_div_account
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getIsDivAccount() {
        return isDivAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.is_div_account
     *
     * @param isDivAccount the value for nplm_contract_attribute.is_div_account
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setIsDivAccount(String isDivAccount) {
        this.isDivAccount = isDivAccount == null ? null : isDivAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.system_type
     *
     * @return the value of nplm_contract_attribute.system_type
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getSystemType() {
        return systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.system_type
     *
     * @param systemType the value for nplm_contract_attribute.system_type
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setSystemType(String systemType) {
        this.systemType = systemType == null ? null : systemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.high_risk
     *
     * @return the value of nplm_contract_attribute.high_risk
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getHighRisk() {
        return highRisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.high_risk
     *
     * @param highRisk the value for nplm_contract_attribute.high_risk
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setHighRisk(String highRisk) {
        this.highRisk = highRisk == null ? null : highRisk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.is_buyout
     *
     * @return the value of nplm_contract_attribute.is_buyout
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getIsBuyout() {
        return isBuyout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.is_buyout
     *
     * @param isBuyout the value for nplm_contract_attribute.is_buyout
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setIsBuyout(String isBuyout) {
        this.isBuyout = isBuyout == null ? null : isBuyout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.fee_process_type
     *
     * @return the value of nplm_contract_attribute.fee_process_type
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getFeeProcessType() {
        return feeProcessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.fee_process_type
     *
     * @param feeProcessType the value for nplm_contract_attribute.fee_process_type
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setFeeProcessType(String feeProcessType) {
        this.feeProcessType = feeProcessType == null ? null : feeProcessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.student_corp_name
     *
     * @return the value of nplm_contract_attribute.student_corp_name
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getStudentCorpName() {
        return studentCorpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.student_corp_name
     *
     * @param studentCorpName the value for nplm_contract_attribute.student_corp_name
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setStudentCorpName(String studentCorpName) {
        this.studentCorpName = studentCorpName == null ? null : studentCorpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.settle_date
     *
     * @return the value of nplm_contract_attribute.settle_date
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getSettleDate() {
        return settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.settle_date
     *
     * @param settleDate the value for nplm_contract_attribute.settle_date
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setSettleDate(String settleDate) {
        this.settleDate = settleDate == null ? null : settleDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.habit_time
     *
     * @return the value of nplm_contract_attribute.habit_time
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getHabitTime() {
        return habitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.habit_time
     *
     * @param habitTime the value for nplm_contract_attribute.habit_time
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setHabitTime(String habitTime) {
        this.habitTime = habitTime == null ? null : habitTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.RepayDay
     *
     * @return the value of nplm_contract_attribute.RepayDay
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getRepayday() {
        return repayday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.RepayDay
     *
     * @param repayday the value for nplm_contract_attribute.RepayDay
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setRepayday(String repayday) {
        this.repayday = repayday == null ? null : repayday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.apply_Id
     *
     * @return the value of nplm_contract_attribute.apply_Id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.apply_Id
     *
     * @param applyId the value for nplm_contract_attribute.apply_Id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.old_Apply_Id
     *
     * @return the value of nplm_contract_attribute.old_Apply_Id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getOldApplyId() {
        return oldApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.old_Apply_Id
     *
     * @param oldApplyId the value for nplm_contract_attribute.old_Apply_Id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setOldApplyId(String oldApplyId) {
        this.oldApplyId = oldApplyId == null ? null : oldApplyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.dept_id
     *
     * @return the value of nplm_contract_attribute.dept_id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.dept_id
     *
     * @param deptId the value for nplm_contract_attribute.dept_id
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.dept_name
     *
     * @return the value of nplm_contract_attribute.dept_name
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.dept_name
     *
     * @param deptName the value for nplm_contract_attribute.dept_name
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.CREATOR
     *
     * @return the value of nplm_contract_attribute.CREATOR
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.CREATOR
     *
     * @param creator the value for nplm_contract_attribute.CREATOR
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.CREATE_TIME
     *
     * @return the value of nplm_contract_attribute.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.CREATE_TIME
     *
     * @param createTime the value for nplm_contract_attribute.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.UPDATER
     *
     * @return the value of nplm_contract_attribute.UPDATER
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.UPDATER
     *
     * @param updater the value for nplm_contract_attribute.UPDATER
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.UPDATE_TIME
     *
     * @return the value of nplm_contract_attribute.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.UPDATE_TIME
     *
     * @param updateTime the value for nplm_contract_attribute.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.UPDATE_TYPE
     *
     * @return the value of nplm_contract_attribute.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getUpdateType() {
        return updateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.UPDATE_TYPE
     *
     * @param updateType the value for nplm_contract_attribute.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setUpdateType(String updateType) {
        this.updateType = updateType == null ? null : updateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.FRONT_CHARGE_DISCOUNT
     *
     * @return the value of nplm_contract_attribute.FRONT_CHARGE_DISCOUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getFrontChargeDiscount() {
        return frontChargeDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.FRONT_CHARGE_DISCOUNT
     *
     * @param frontChargeDiscount the value for nplm_contract_attribute.FRONT_CHARGE_DISCOUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setFrontChargeDiscount(Integer frontChargeDiscount) {
        this.frontChargeDiscount = frontChargeDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.MONTH_M_RATE
     *
     * @return the value of nplm_contract_attribute.MONTH_M_RATE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getMonthMRate() {
        return monthMRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.MONTH_M_RATE
     *
     * @param monthMRate the value for nplm_contract_attribute.MONTH_M_RATE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setMonthMRate(Integer monthMRate) {
        this.monthMRate = monthMRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.HANDLE_CHARGE_RATE
     *
     * @return the value of nplm_contract_attribute.HANDLE_CHARGE_RATE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getHandleChargeRate() {
        return handleChargeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.HANDLE_CHARGE_RATE
     *
     * @param handleChargeRate the value for nplm_contract_attribute.HANDLE_CHARGE_RATE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setHandleChargeRate(Integer handleChargeRate) {
        this.handleChargeRate = handleChargeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.LOAN_TIMES
     *
     * @return the value of nplm_contract_attribute.LOAN_TIMES
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getLoanTimes() {
        return loanTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.LOAN_TIMES
     *
     * @param loanTimes the value for nplm_contract_attribute.LOAN_TIMES
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setLoanTimes(Integer loanTimes) {
        this.loanTimes = loanTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.PAWN
     *
     * @return the value of nplm_contract_attribute.PAWN
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getPawn() {
        return pawn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.PAWN
     *
     * @param pawn the value for nplm_contract_attribute.PAWN
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setPawn(String pawn) {
        this.pawn = pawn == null ? null : pawn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.HANDLE_CHARGE
     *
     * @return the value of nplm_contract_attribute.HANDLE_CHARGE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getHandleCharge() {
        return handleCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.HANDLE_CHARGE
     *
     * @param handleCharge the value for nplm_contract_attribute.HANDLE_CHARGE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setHandleCharge(Integer handleCharge) {
        this.handleCharge = handleCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.MONTH_CHARGE_DISCOUNT
     *
     * @return the value of nplm_contract_attribute.MONTH_CHARGE_DISCOUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getMonthChargeDiscount() {
        return monthChargeDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.MONTH_CHARGE_DISCOUNT
     *
     * @param monthChargeDiscount the value for nplm_contract_attribute.MONTH_CHARGE_DISCOUNT
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setMonthChargeDiscount(Integer monthChargeDiscount) {
        this.monthChargeDiscount = monthChargeDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.GUARANTEE_FEE
     *
     * @return the value of nplm_contract_attribute.GUARANTEE_FEE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public Integer getGuaranteeFee() {
        return guaranteeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.GUARANTEE_FEE
     *
     * @param guaranteeFee the value for nplm_contract_attribute.GUARANTEE_FEE
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setGuaranteeFee(Integer guaranteeFee) {
        this.guaranteeFee = guaranteeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.GUARANTEE_COMPANY
     *
     * @return the value of nplm_contract_attribute.GUARANTEE_COMPANY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getGuaranteeCompany() {
        return guaranteeCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.GUARANTEE_COMPANY
     *
     * @param guaranteeCompany the value for nplm_contract_attribute.GUARANTEE_COMPANY
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setGuaranteeCompany(String guaranteeCompany) {
        this.guaranteeCompany = guaranteeCompany == null ? null : guaranteeCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.def1
     *
     * @return the value of nplm_contract_attribute.def1
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getDef1() {
        return def1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.def1
     *
     * @param def1 the value for nplm_contract_attribute.def1
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setDef1(String def1) {
        this.def1 = def1 == null ? null : def1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.def2
     *
     * @return the value of nplm_contract_attribute.def2
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getDef2() {
        return def2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.def2
     *
     * @param def2 the value for nplm_contract_attribute.def2
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setDef2(String def2) {
        this.def2 = def2 == null ? null : def2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.def3
     *
     * @return the value of nplm_contract_attribute.def3
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getDef3() {
        return def3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.def3
     *
     * @param def3 the value for nplm_contract_attribute.def3
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setDef3(String def3) {
        this.def3 = def3 == null ? null : def3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.def4
     *
     * @return the value of nplm_contract_attribute.def4
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getDef4() {
        return def4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.def4
     *
     * @param def4 the value for nplm_contract_attribute.def4
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setDef4(String def4) {
        this.def4 = def4 == null ? null : def4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.def5
     *
     * @return the value of nplm_contract_attribute.def5
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getDef5() {
        return def5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.def5
     *
     * @param def5 the value for nplm_contract_attribute.def5
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setDef5(String def5) {
        this.def5 = def5 == null ? null : def5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.def6
     *
     * @return the value of nplm_contract_attribute.def6
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getDef6() {
        return def6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.def6
     *
     * @param def6 the value for nplm_contract_attribute.def6
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setDef6(String def6) {
        this.def6 = def6 == null ? null : def6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.def7
     *
     * @return the value of nplm_contract_attribute.def7
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getDef7() {
        return def7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.def7
     *
     * @param def7 the value for nplm_contract_attribute.def7
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setDef7(String def7) {
        this.def7 = def7 == null ? null : def7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.def8
     *
     * @return the value of nplm_contract_attribute.def8
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getDef8() {
        return def8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.def8
     *
     * @param def8 the value for nplm_contract_attribute.def8
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setDef8(String def8) {
        this.def8 = def8 == null ? null : def8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.def9
     *
     * @return the value of nplm_contract_attribute.def9
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getDef9() {
        return def9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.def9
     *
     * @param def9 the value for nplm_contract_attribute.def9
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setDef9(String def9) {
        this.def9 = def9 == null ? null : def9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_contract_attribute.def10
     *
     * @return the value of nplm_contract_attribute.def10
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public String getDef10() {
        return def10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_contract_attribute.def10
     *
     * @param def10 the value for nplm_contract_attribute.def10
     *
     * @mbggenerated Mon Sep 17 13:23:03 CST 2018
     */
    public void setDef10(String def10) {
        this.def10 = def10 == null ? null : def10.trim();
    }
}