package com.atguigu.finance.bean;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;

public class NplmRepaymentPlan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Id
    @Column
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.LOAN_CONTRACT_NUM
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer loanContractNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.INSTALMENT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer instalment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.PRE_REPAYMENT_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Date preRepaymentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.REPAYMENT_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Date repaymentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer capital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer interest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.INSTALLMENT_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer installmentFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer amerce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer forfeit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.PENALTY
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer penalty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.change_fee
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer changeFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.OTHER_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer otherFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.REPAYMENT_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer repaymentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.INDEED_CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer indeedCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.INDEED_INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer indeedInterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.INDEED_INST_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer indeedInstFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.INDEED_AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer indeedAmerce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.INDEED_FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer indeedForfeit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.indeed_penalty
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer indeedPenalty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.indeed_change_fee
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer indeedChangeFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.indeed_OTHER_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer indeedOtherFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.INDEED_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer indeedAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.reduce_CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer reduceCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.reduce_INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer reduceInterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.reduce_AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer reduceAmerce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.reduce_FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer reduceForfeit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.reduce_INST_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer reduceInstFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.reduce_penalty
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer reducePenalty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.reduce_PRE_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer reducePreFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.reduce_OTHER_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer reduceOtherFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.REMAIN_CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer remainCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.NPV_remain_capital
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer npvRemainCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.ALL_REPAYMENT_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Integer allRepaymentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.REPAYMENT_STATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String repaymentState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.REMARK
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.CREATOR
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.UPDATER
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.IS_OPERATING
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String isOperating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nplm_repayment_plan.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    @Column
    private String updateType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.ID
     *
     * @return the value of nplm_repayment_plan.ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.ID
     *
     * @param id the value for nplm_repayment_plan.ID
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.LOAN_CONTRACT_NUM
     *
     * @return the value of nplm_repayment_plan.LOAN_CONTRACT_NUM
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getLoanContractNum() {
        return loanContractNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.LOAN_CONTRACT_NUM
     *
     * @param loanContractNum the value for nplm_repayment_plan.LOAN_CONTRACT_NUM
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setLoanContractNum(Integer loanContractNum) {
        this.loanContractNum = loanContractNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.INSTALMENT
     *
     * @return the value of nplm_repayment_plan.INSTALMENT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getInstalment() {
        return instalment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.INSTALMENT
     *
     * @param instalment the value for nplm_repayment_plan.INSTALMENT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setInstalment(Integer instalment) {
        this.instalment = instalment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.PRE_REPAYMENT_DATE
     *
     * @return the value of nplm_repayment_plan.PRE_REPAYMENT_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Date getPreRepaymentDate() {
        return preRepaymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.PRE_REPAYMENT_DATE
     *
     * @param preRepaymentDate the value for nplm_repayment_plan.PRE_REPAYMENT_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setPreRepaymentDate(Date preRepaymentDate) {
        this.preRepaymentDate = preRepaymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.REPAYMENT_DATE
     *
     * @return the value of nplm_repayment_plan.REPAYMENT_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Date getRepaymentDate() {
        return repaymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.REPAYMENT_DATE
     *
     * @param repaymentDate the value for nplm_repayment_plan.REPAYMENT_DATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setRepaymentDate(Date repaymentDate) {
        this.repaymentDate = repaymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.CAPITAL
     *
     * @return the value of nplm_repayment_plan.CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getCapital() {
        return capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.CAPITAL
     *
     * @param capital the value for nplm_repayment_plan.CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setCapital(Integer capital) {
        this.capital = capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.INTEREST
     *
     * @return the value of nplm_repayment_plan.INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.INTEREST
     *
     * @param interest the value for nplm_repayment_plan.INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setInterest(Integer interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.INSTALLMENT_FEE
     *
     * @return the value of nplm_repayment_plan.INSTALLMENT_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getInstallmentFee() {
        return installmentFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.INSTALLMENT_FEE
     *
     * @param installmentFee the value for nplm_repayment_plan.INSTALLMENT_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setInstallmentFee(Integer installmentFee) {
        this.installmentFee = installmentFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.AMERCE
     *
     * @return the value of nplm_repayment_plan.AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getAmerce() {
        return amerce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.AMERCE
     *
     * @param amerce the value for nplm_repayment_plan.AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAmerce(Integer amerce) {
        this.amerce = amerce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.FORFEIT
     *
     * @return the value of nplm_repayment_plan.FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getForfeit() {
        return forfeit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.FORFEIT
     *
     * @param forfeit the value for nplm_repayment_plan.FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setForfeit(Integer forfeit) {
        this.forfeit = forfeit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.PENALTY
     *
     * @return the value of nplm_repayment_plan.PENALTY
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getPenalty() {
        return penalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.PENALTY
     *
     * @param penalty the value for nplm_repayment_plan.PENALTY
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setPenalty(Integer penalty) {
        this.penalty = penalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.change_fee
     *
     * @return the value of nplm_repayment_plan.change_fee
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getChangeFee() {
        return changeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.change_fee
     *
     * @param changeFee the value for nplm_repayment_plan.change_fee
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setChangeFee(Integer changeFee) {
        this.changeFee = changeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.OTHER_FEE
     *
     * @return the value of nplm_repayment_plan.OTHER_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getOtherFee() {
        return otherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.OTHER_FEE
     *
     * @param otherFee the value for nplm_repayment_plan.OTHER_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setOtherFee(Integer otherFee) {
        this.otherFee = otherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.REPAYMENT_AMOUNT
     *
     * @return the value of nplm_repayment_plan.REPAYMENT_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getRepaymentAmount() {
        return repaymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.REPAYMENT_AMOUNT
     *
     * @param repaymentAmount the value for nplm_repayment_plan.REPAYMENT_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setRepaymentAmount(Integer repaymentAmount) {
        this.repaymentAmount = repaymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.INDEED_CAPITAL
     *
     * @return the value of nplm_repayment_plan.INDEED_CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getIndeedCapital() {
        return indeedCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.INDEED_CAPITAL
     *
     * @param indeedCapital the value for nplm_repayment_plan.INDEED_CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIndeedCapital(Integer indeedCapital) {
        this.indeedCapital = indeedCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.INDEED_INTEREST
     *
     * @return the value of nplm_repayment_plan.INDEED_INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getIndeedInterest() {
        return indeedInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.INDEED_INTEREST
     *
     * @param indeedInterest the value for nplm_repayment_plan.INDEED_INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIndeedInterest(Integer indeedInterest) {
        this.indeedInterest = indeedInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.INDEED_INST_FEE
     *
     * @return the value of nplm_repayment_plan.INDEED_INST_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getIndeedInstFee() {
        return indeedInstFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.INDEED_INST_FEE
     *
     * @param indeedInstFee the value for nplm_repayment_plan.INDEED_INST_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIndeedInstFee(Integer indeedInstFee) {
        this.indeedInstFee = indeedInstFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.INDEED_AMERCE
     *
     * @return the value of nplm_repayment_plan.INDEED_AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getIndeedAmerce() {
        return indeedAmerce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.INDEED_AMERCE
     *
     * @param indeedAmerce the value for nplm_repayment_plan.INDEED_AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIndeedAmerce(Integer indeedAmerce) {
        this.indeedAmerce = indeedAmerce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.INDEED_FORFEIT
     *
     * @return the value of nplm_repayment_plan.INDEED_FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getIndeedForfeit() {
        return indeedForfeit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.INDEED_FORFEIT
     *
     * @param indeedForfeit the value for nplm_repayment_plan.INDEED_FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIndeedForfeit(Integer indeedForfeit) {
        this.indeedForfeit = indeedForfeit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.indeed_penalty
     *
     * @return the value of nplm_repayment_plan.indeed_penalty
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getIndeedPenalty() {
        return indeedPenalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.indeed_penalty
     *
     * @param indeedPenalty the value for nplm_repayment_plan.indeed_penalty
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIndeedPenalty(Integer indeedPenalty) {
        this.indeedPenalty = indeedPenalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.indeed_change_fee
     *
     * @return the value of nplm_repayment_plan.indeed_change_fee
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getIndeedChangeFee() {
        return indeedChangeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.indeed_change_fee
     *
     * @param indeedChangeFee the value for nplm_repayment_plan.indeed_change_fee
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIndeedChangeFee(Integer indeedChangeFee) {
        this.indeedChangeFee = indeedChangeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.indeed_OTHER_FEE
     *
     * @return the value of nplm_repayment_plan.indeed_OTHER_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getIndeedOtherFee() {
        return indeedOtherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.indeed_OTHER_FEE
     *
     * @param indeedOtherFee the value for nplm_repayment_plan.indeed_OTHER_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIndeedOtherFee(Integer indeedOtherFee) {
        this.indeedOtherFee = indeedOtherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.INDEED_AMOUNT
     *
     * @return the value of nplm_repayment_plan.INDEED_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getIndeedAmount() {
        return indeedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.INDEED_AMOUNT
     *
     * @param indeedAmount the value for nplm_repayment_plan.INDEED_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIndeedAmount(Integer indeedAmount) {
        this.indeedAmount = indeedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.reduce_CAPITAL
     *
     * @return the value of nplm_repayment_plan.reduce_CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getReduceCapital() {
        return reduceCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.reduce_CAPITAL
     *
     * @param reduceCapital the value for nplm_repayment_plan.reduce_CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setReduceCapital(Integer reduceCapital) {
        this.reduceCapital = reduceCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.reduce_INTEREST
     *
     * @return the value of nplm_repayment_plan.reduce_INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getReduceInterest() {
        return reduceInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.reduce_INTEREST
     *
     * @param reduceInterest the value for nplm_repayment_plan.reduce_INTEREST
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setReduceInterest(Integer reduceInterest) {
        this.reduceInterest = reduceInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.reduce_AMERCE
     *
     * @return the value of nplm_repayment_plan.reduce_AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getReduceAmerce() {
        return reduceAmerce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.reduce_AMERCE
     *
     * @param reduceAmerce the value for nplm_repayment_plan.reduce_AMERCE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setReduceAmerce(Integer reduceAmerce) {
        this.reduceAmerce = reduceAmerce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.reduce_FORFEIT
     *
     * @return the value of nplm_repayment_plan.reduce_FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getReduceForfeit() {
        return reduceForfeit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.reduce_FORFEIT
     *
     * @param reduceForfeit the value for nplm_repayment_plan.reduce_FORFEIT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setReduceForfeit(Integer reduceForfeit) {
        this.reduceForfeit = reduceForfeit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.reduce_INST_FEE
     *
     * @return the value of nplm_repayment_plan.reduce_INST_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getReduceInstFee() {
        return reduceInstFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.reduce_INST_FEE
     *
     * @param reduceInstFee the value for nplm_repayment_plan.reduce_INST_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setReduceInstFee(Integer reduceInstFee) {
        this.reduceInstFee = reduceInstFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.reduce_penalty
     *
     * @return the value of nplm_repayment_plan.reduce_penalty
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getReducePenalty() {
        return reducePenalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.reduce_penalty
     *
     * @param reducePenalty the value for nplm_repayment_plan.reduce_penalty
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setReducePenalty(Integer reducePenalty) {
        this.reducePenalty = reducePenalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.reduce_PRE_FEE
     *
     * @return the value of nplm_repayment_plan.reduce_PRE_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getReducePreFee() {
        return reducePreFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.reduce_PRE_FEE
     *
     * @param reducePreFee the value for nplm_repayment_plan.reduce_PRE_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setReducePreFee(Integer reducePreFee) {
        this.reducePreFee = reducePreFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.reduce_OTHER_FEE
     *
     * @return the value of nplm_repayment_plan.reduce_OTHER_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getReduceOtherFee() {
        return reduceOtherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.reduce_OTHER_FEE
     *
     * @param reduceOtherFee the value for nplm_repayment_plan.reduce_OTHER_FEE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setReduceOtherFee(Integer reduceOtherFee) {
        this.reduceOtherFee = reduceOtherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.REMAIN_CAPITAL
     *
     * @return the value of nplm_repayment_plan.REMAIN_CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getRemainCapital() {
        return remainCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.REMAIN_CAPITAL
     *
     * @param remainCapital the value for nplm_repayment_plan.REMAIN_CAPITAL
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setRemainCapital(Integer remainCapital) {
        this.remainCapital = remainCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.NPV_remain_capital
     *
     * @return the value of nplm_repayment_plan.NPV_remain_capital
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getNpvRemainCapital() {
        return npvRemainCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.NPV_remain_capital
     *
     * @param npvRemainCapital the value for nplm_repayment_plan.NPV_remain_capital
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setNpvRemainCapital(Integer npvRemainCapital) {
        this.npvRemainCapital = npvRemainCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.ALL_REPAYMENT_AMOUNT
     *
     * @return the value of nplm_repayment_plan.ALL_REPAYMENT_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Integer getAllRepaymentAmount() {
        return allRepaymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.ALL_REPAYMENT_AMOUNT
     *
     * @param allRepaymentAmount the value for nplm_repayment_plan.ALL_REPAYMENT_AMOUNT
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setAllRepaymentAmount(Integer allRepaymentAmount) {
        this.allRepaymentAmount = allRepaymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.REPAYMENT_STATE
     *
     * @return the value of nplm_repayment_plan.REPAYMENT_STATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getRepaymentState() {
        return repaymentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.REPAYMENT_STATE
     *
     * @param repaymentState the value for nplm_repayment_plan.REPAYMENT_STATE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setRepaymentState(String repaymentState) {
        this.repaymentState = repaymentState == null ? null : repaymentState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.REMARK
     *
     * @return the value of nplm_repayment_plan.REMARK
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.REMARK
     *
     * @param remark the value for nplm_repayment_plan.REMARK
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.CREATOR
     *
     * @return the value of nplm_repayment_plan.CREATOR
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.CREATOR
     *
     * @param creator the value for nplm_repayment_plan.CREATOR
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.CREATE_TIME
     *
     * @return the value of nplm_repayment_plan.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.CREATE_TIME
     *
     * @param createTime the value for nplm_repayment_plan.CREATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.UPDATER
     *
     * @return the value of nplm_repayment_plan.UPDATER
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.UPDATER
     *
     * @param updater the value for nplm_repayment_plan.UPDATER
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.UPDATE_TIME
     *
     * @return the value of nplm_repayment_plan.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.UPDATE_TIME
     *
     * @param updateTime the value for nplm_repayment_plan.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.IS_OPERATING
     *
     * @return the value of nplm_repayment_plan.IS_OPERATING
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getIsOperating() {
        return isOperating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.IS_OPERATING
     *
     * @param isOperating the value for nplm_repayment_plan.IS_OPERATING
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setIsOperating(String isOperating) {
        this.isOperating = isOperating == null ? null : isOperating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nplm_repayment_plan.UPDATE_TYPE
     *
     * @return the value of nplm_repayment_plan.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public String getUpdateType() {
        return updateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nplm_repayment_plan.UPDATE_TYPE
     *
     * @param updateType the value for nplm_repayment_plan.UPDATE_TYPE
     *
     * @mbggenerated Mon Sep 17 12:59:57 CST 2018
     */
    public void setUpdateType(String updateType) {
        this.updateType = updateType == null ? null : updateType.trim();
    }
}